7.2 english manual
ALTIBASE/Documents pull request #135
Opened 2021-12-03 06:45 UTC by haeinnmin

7.2 영문 매뉴얼에 부재한 부분들을 추가하였습니다.

2021-12-07 07:10 UTC, eheejung reviewed
일부 리뷰 남겼습니다. 남은 것은 다음에...

2021-12-08 04:14 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains the adminview.sql script file, which creates views related to Altibase system information, as well as other script files for creating stored procedures that are used to view i
세션 정보, 테이블, 인덱스, 이중화 등 데이터베이스 객체 정보의 조회를 용이하게 하는 뷰, 저장 프로시저를 생성하는 스크립트들, Altibase 서버 부하 발생 시 Altibase 상태를 모니터링하기 위한 스크립트들이 있는 디렉터리이다.

- 다른 디렉터리에 대한 설명도 '~~가 있는 디렉터리이다.' 형식이라 맞췄습니다.
- 어차피 두 문장 모두 디렉터리에 무엇이 있나 설명하는 내용이라 한 문장이어도 될 것 같아 합쳤습니다.
- 뷰가 중복되어 앞 부분에는 삭제하였습니다.

변경된 문장 검토 부탁드립니다.

2021-12-08 04:32 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains information about Altibase product which was installed by Altibase package installer.
반영했습니다.

2021-12-08 04:32 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains xml configuration files, shell scripts, sql files, log directories required to run altiMon(Altibase Monitoring Daemon). For more information about the subdirectories, please r
반영했습니다.

2021-12-08 04:35 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains backup log files for recovery. The location and name of this directory must be specified in the altibase.properties file.
넵. 반영하겠습니다. 확인 중에 국문 매뉴얼을 다시 확인해보았는데, 문장이 어색한 것 같아 수정하면 어떨까 합니다.

복구를 위해 로그 파일을 백업하는 백업 디렉토리이다.
-> 복구를 위해 백업해두는 로그 파일이 존재하는 디렉터리이다.

2021-12-08 04:41 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains backup log files for recovery. The location and name of this directory must be specified in the altibase.properties file.
그런데 희정님께서 첨부해주신 링크를 확인해 보아도 로그 파일을 Log Files로 사용하고 있지는 않는 것 같습니다. 사용자도 매뉴얼을 읽다가 왜 대명사처럼 Log Files로 표시되어 있나 의문을 가질 것 같구요. 혹시 헷갈리실까 우려되신다면 차라리 이 부분의 log file을 redo log file로 변경하는 건 어떨까요? 아니면 Log Files로 표기하고 링크를 걸까요?

2021-12-08 06:43 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +-   syspassword: the file password of sys user is stored. For more detailed information on how to use this file, please refer to the *Utilities Manual*.
반영했습니다.

2021-12-08 06:59 UTC, eheejung commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains backup log files for recovery. The location and name of this directory must be specified in the altibase.properties file.
이거 그냥 지나갔는데, 아카이브 로그 파일 이라고 해도 됩니다. 
복구를 위해 로그 파일을 백업하는 백업 디렉토리이다.
-> 복구를 위해 백업해두는 로그 파일이 존재하는 디렉터리이다.
--> 아카이브 로그 파일이 있는 디렉토리이다.  

아카이브 로그 파일에 대한 설명은 https://github.com/ALTIBASE/Documents/blob/master/Manuals/Altibase_7.2/kor/Administrator's%20Manual.md#%EB%A1%9C%EA%B7%B8-%ED%8C%8C%EC%9D%BC 에 있고요. 

네. 전체적으로 Log Files을 사용하고 있지는 않습니다. 한글 매뉴얼은 용어가 "로그 파일" 로 구분이 안 되지만 영문은 Log Files 로 구분이 가능하니 의견 내 봤습니다. 일괄 적용해야하는 부분이기는 합니다. 
여기서는 의견을 내 주셔서 archive log file 이라고 하고 용어 통일은 추후에 진행하도록 하지요. 
로그 파일이 좀 복잡합니다.

2021-12-08 07:04 UTC, eheejung commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains the adminview.sql script file, which creates views related to Altibase system information, as well as other script files for creating stored procedures that are used to view i
네. 좋습니다. 
더 간단하게 아래 문장이 어떨지요? 문서는 보고 또 보면 계속 새롭게 나오네요. ㅎㅎ

데이터베이스 객체 정보를 조회하는 뷰, 저장 프로시저 생성 스크립트와 Altibase 상태를 모니터링하기 위한 스크립트들이 있는 디렉토리이다.

2021-12-08 08:32 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains the adminview.sql script file, which creates views related to Altibase system information, as well as other script files for creating stored procedures that are used to view i
넵. 이렇게 수정하도록 하겠습니다.

2021-12-08 08:35 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains backup log files for recovery. The location and name of this directory must be specified in the altibase.properties file.
넵, 현재는 아카이브 로그 파일로 반영했습니다.

2021-12-08 08:35 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains system defined stored packages and catproc.sql file which is a package creating script. For more information about the subdirectories, please refer to the Altibase Stored Pack
Altibase 7.2 Stored Procedures Manual 을 참고한다.
위 문장으로 반영했습니다.

2021-12-08 08:36 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Administrator's Manual.md
> +This directory contains scripts or libraries required to connect to 3rd parties.
반영했습니다.

2021-12-08 08:36 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/General Reference-1.Data Types & Altibase Properties.md
> -
반영했습니다.

2021-12-08 08:36 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
반영했습니다.

2021-12-09 01:30 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +### SYS_REPL_OLD_CHECK_COLUMNS_
반영했습니다.

2021-12-09 05:22 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +| TABLE_OID        | BIGINT        | The object identifier of  the table                     |
위처럼 기존에 작업해놓으셔서 그대로 했었는데, the table object identifier로 전체 수정하겠습니다~

2021-12-09 05:30 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +| CONSTRAINT_ID    | INTEGER       | The CHECK constraint identifier                         |
CHECK constraint 아닌가요?
https://en.wikipedia.org/wiki/Check_constraint

2021-12-14 23:46 UTC, zennken requested changes
가능한 한글 매뉴얼과 일관성 있게 변경하는 것이 좋을 것 같아 수정 요청드립니다.

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center User's Manual를 참고하라.
참고하라는 명령조 같아서, 참고한다는 어떨런지요?

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- 도착 데이터베이스
한글 매뉴얼과 일관성을 유지하기 위해 대상 데이터베이스 용어를 쓰는 것이 좋을 것 같습니다.

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +##### 도착 데이터베이스: Oracle
한글 매뉴얼과 일관성을 유지하기 위해 대상 데이터베이스 용어를 쓰는 것이 좋을 것 같습니다.

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 4.3.9 혹은 그 이상
매뉴얼과 일관성있게 Altibase: 4.3.9 이상 버전 으로 하면 좋을 것 같습니다.

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- Altibase 7.1 또는 그 이상
한글 매뉴얼과 일관성을 유지하기 위해 Altibase 7.1 이상 버전 으로 하는 것이 좋을 것 같습니다.

2021-12-14 23:46 UTC, zennken commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- Java: Oracle, OpenJDK 또는 IBM Java Runtime Environment 8 또는 그 이상
한글 매뉴얼과 일관성을 유지하기 위해 8 이상 버전 으로 수정하면 좋을 것 같습니다.

2021-12-15 00:37 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- 도착 데이터베이스
반영하였습니다.

2021-12-15 00:53 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +
반영했습니다.

2021-12-15 01:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +| Apache log4j         | 1.2.16  | Homepage: https://logging.apache.org/log4j/ License: Apache License 2.0(http://www.apache.org/licenses/LICENSE-2.0.txt) |
반영하였습니다.

2021-12-15 01:42 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +https://github.com/ALTIBASE/Documents/blob/master/Manuals/Altibase_7.1/kor/altiShapeLoader.md
반영했습니다.

2021-12-15 01:43 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +https://github.com/ALTIBASE/Documents/blob/master/Manuals/Altibase_7.1/kor/MigrationCenter.md
반영했습니다.

2021-12-15 01:43 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center User's Manual를 참고하라.
반영했습니다.

2021-12-15 01:44 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- 도착 데이터베이스
반영했습니다.

2021-12-15 01:44 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +##### 도착 데이터베이스: Oracle
반영했습니다.

2021-12-15 01:45 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 4.3.9 혹은 그 이상
반영했습니다.

2021-12-15 01:45 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- Altibase 7.1 또는 그 이상
반영했습니다.

2021-12-15 01:45 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- Java: Oracle, OpenJDK 또는 IBM Java Runtime Environment 8 또는 그 이상
반영했습니다.

2021-12-15 01:58 UTC, eheejung reviewed
리뷰 남깁니다.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 클라이언트의 하드웨어나 OS가 아닌 JAVA Runtime Environment (JRE)에 의존하는 완전히 Java를 기반으로 하는 클라이언트 어플리케이션이다. 단, Migration Center를 GUI 모드로 실행하기 위해 그래픽 라이브러리나 OS의 추가적인 지원을 필요로 한다.
영어가 한 문장이라고 한글도 한 문장으로 할 필요는 없을 것 같습니다. 반대도 마찬가지고요. 
강조하는 내용을 앞쪽으로 두면 좋겠습니다. 
IT쪽 문서를 보면 Pure는 '완전히' 보다는 '순수한' 이라는 용어를 많이 씁니다. 

Migration Center는 순수 Java 기반 클라이언트 애플리케이션으로, 클라이언트의 하드웨어나 OS 대신 JAVA Runtime Environment (JRE)에 의존한다. 단, Migration Center를 GUI 모드로 실행하기 위해 운영 체제의 그래픽 라이브러리에 대한 추가 지원이 필요하다.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- Altibase Migration Center 7.9 Release Notes
Release Notes -> 한글로 변경해주세요.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +------
선이 하나 더 들어가있네요. 삭제해주세요.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 데이터베이스 마이그레이션을 위한 도구로서, 사용자가 편리하게 써드파티 데이터베이스를 알티베이스 데이터베이스 또는 외부 파일로 이동하거나 알티베이스 데이터베이스를 오라클 데이터베이스로 이전하도록 한다. 보통 데이터베이스 마이그레이션은 수동으로 진행할 경우 복잡하고 시간이 많이 소요되며 에러가 발생하는 불편함이 있다. 이를 개
이동, 이전 보다 이관 이라는 단어를 사용합니다.

prone to human error 에러가 발생하는 불편함이 있다.
-> '휴먼 에러'는 많이 사용하는 용어라 그대로 사용해도 될 것 같습니다.  '사용자 부주의로 인한 오류' 로 표현해도 되고요. 

이를 개선하기 위해 -> '개선'은 잘못된 것을 고친다는,, 그런 의미가 있습니다. 
국어사전 : 잘못된 것이나 부족한 것, 나쁜 것 따위를 고쳐 더 좋게 만들다.
개선보다는 다른 단어를 사용해주세요. 

이에 더하여, 자원 사용을 최적화히기 위해 CLI 모드 또한 지원한다.
-> '이에 더하여' 와 '또한' 이 중복됩니다. 
-> 이에 더하여, 자원 사용을 최적화히기 위해 CLI 모드도 지원한다.
-> 또한, 자원 사용을 최적화히기 위해 CLI 모드도 지원한다.
-> 오타도 있네요.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- Tibero 4 sp1로부터의 데이터베이스 이전 지원
원본 데이터베이스로 Tibero 4 sp1 지원

@zennken 매뉴얼에는 Tibero: 4sp1~6 로 나와있는데 통일해야 하지 않을까요?

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| BUG-47352 | Reconcile 중 파티션드 테이블 변환 단계에서 변경사항 일부가 Next 또는 Back 후에 돌아오면 휘발된다. |
Reconcile 중 파티션드 테이블 변환 단계에서 변경사항 일부가 Next 또는 Back 후에 돌아오면 휘발된다.
-> BUG-47352 버그 제목 확인하시고 그대로 사용하면 좋을 것 같습니다. 
-> 가능한 쉬운 단어를 사용하는 것이 좋겠습니다. '휘발' 보다는 사라진다.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| 7.9                            |
@zennken 이 표 보다는 Migration Center 버전이 7.8에서 7.9로 변경되었다. 

라는 문장이 어떨지요?

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 4.3.9 혹은 그 이상
네. 
혹은 그 이상 -> 이상 으로 변경하면 좋겠습니다.

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 5.5.1 혹은 그 이상
혹은 그 이상 -> 이상

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center is based on the following open-source libraries. The licenses are distributed in a text file format along with Migration Center.
영문 삭제

2021-12-15 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| Sun or IBM Java 5 or higher | MigrationCenter7.9.zip MigrationCenter7.9.tar.gz |
Sun or IBM Java 5 or higher 한글화

2021-12-15 02:50 UTC, eheejung reviewed
리뷰 남깁니다.

2021-12-15 02:50 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +    - [5.3 설치](#5.3 설치)
링크 생성 필요

2021-12-15 02:50 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader는 shapefile 내보내기와 불러오기를 위한 도구로, Java를 기반으로 한 오픈소스 라이브러리인 GeoTools를 사용하여 작성되었다.
shapefile -> 쉐이프 파일(Shapefile) 
불러오기 -> 가져오기 

shapefile 내보내기와 불러오기를 -> shapefile 가져오기와 내보내기
순서를 아래 설명과 맞추면 좋겠네요. 

용어 사용은 매뉴얼을 참고해주세요.

2021-12-15 02:50 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader는 shapefile 내보내기와 불러오기를 위한 도구로, Java를 기반으로 한 오픈소스 라이브러리인 GeoTools를 사용하여 작성되었다.
Java를 기반으로 한 오픈소스 라이브러리인 GeoTools
-> Java 기반의 오픈소스 라이브러리 GeoTools

2021-12-15 02:50 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +Shapefile을 불러오기는 좌표 정보, 속성 정보와 같은 공간 데이터 정보를 Shapefile로부터 알티베이스 데이터베이스 테이블에 삽입하는 것을 의미한다. Shapefile 내보내기는 알티베이스 데이터베이스 테이블에 저장된 공간 데이터 정보를 사용하여 Shapefile을 생성하는 것을 의미한다.
Shapefile을 불러오기 -> Shapefile 가져오기
좌표 정보, 속성 정보와 같은 공간 데이터 정보 -> 좌표 및 좌표 속성과 같은 공간 데이터 정보

2021-12-15 02:50 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- 64bit OS Java에서 설치 및 실행 가능
64bit OS Java에서 설치 및 실행 가능 -> Java 설치 및 구동 가능한 64bit OS

2021-12-15 04:08 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 5.5.1 혹은 그 이상
반영하였습니다.

2021-12-15 04:08 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +  - Altibase : Altibase 4.3.9 혹은 그 이상
반영하였습니다.

2021-12-15 04:59 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +    - [2.5 다운로드](#2.5 다운로드)
md 파일 내 링크를 말씀하시는 거라면 저는 해당위치로 이동이 되는데, 혹시 깃헙 링크를 말씀하시는 건가요?

2021-12-15 05:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| CLI mode | Sun of IBM Java 5 or higher | Not required       |
반영했습니다.

2021-12-15 05:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- 화면 해상도: 1024 * 768 픽셀 혹은 그 이상
반영했습니다.

2021-12-15 05:31 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- Altibase Migration Center 7.9 Release Notes
반영했습니다.

2021-12-15 05:32 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +------
반영했습니다.

2021-12-15 05:32 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 클라이언트의 하드웨어나 OS가 아닌 JAVA Runtime Environment (JRE)에 의존하는 완전히 Java를 기반으로 하는 클라이언트 어플리케이션이다. 단, Migration Center를 GUI 모드로 실행하기 위해 그래픽 라이브러리나 OS의 추가적인 지원을 필요로 한다.
반영했습니다.

2021-12-15 05:40 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 데이터베이스 마이그레이션을 위한 도구로서, 사용자가 편리하게 써드파티 데이터베이스를 알티베이스 데이터베이스 또는 외부 파일로 이동하거나 알티베이스 데이터베이스를 오라클 데이터베이스로 이전하도록 한다. 보통 데이터베이스 마이그레이션은 수동으로 진행할 경우 복잡하고 시간이 많이 소요되며 에러가 발생하는 불편함이 있다. 이를 개
반영했습니다.

2021-12-15 05:41 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- Tibero 4 sp1로부터의 데이터베이스 이전 지원
반영했습니다.

2021-12-15 05:42 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| BUG-47352 | Reconcile 중 파티션드 테이블 변환 단계에서 변경사항 일부가 Next 또는 Back 후에 돌아오면 휘발된다. |
'유지되지 않는다.'라는 기존 제목이 조금 더 헷갈릴 수 있을 거라 판단하여 유의어를 사용했는데 그대로 사용하도록 하였습니다.

2021-12-15 05:44 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center is based on the following open-source libraries. The licenses are distributed in a text file format along with Migration Center.
반영했습니다.

2021-12-15 06:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| Sun or IBM Java 5 or higher | MigrationCenter7.9.zip MigrationCenter7.9.tar.gz |
반영했습니다.

2021-12-15 06:16 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader는 shapefile 내보내기와 불러오기를 위한 도구로, Java를 기반으로 한 오픈소스 라이브러리인 GeoTools를 사용하여 작성되었다.
https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=&qna_seq=179461&pageIndex=1

여기에 따르면 표준어는 쉐이프가 아닌 셰이프라는데, 용어 수정하는 게 좋을까요?

2021-12-15 06:18 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +Shapefile을 불러오기는 좌표 정보, 속성 정보와 같은 공간 데이터 정보를 Shapefile로부터 알티베이스 데이터베이스 테이블에 삽입하는 것을 의미한다. Shapefile 내보내기는 알티베이스 데이터베이스 테이블에 저장된 공간 데이터 정보를 사용하여 Shapefile을 생성하는 것을 의미한다.
반영했습니다.

2021-12-15 06:18 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +- 64bit OS Java에서 설치 및 실행 가능
반영했습니다.

2021-12-15 06:28 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader는 shapefile 내보내기와 불러오기를 위한 도구로, Java를 기반으로 한 오픈소스 라이브러리인 GeoTools를 사용하여 작성되었다.
> https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=&qna_seq=179461&pageIndex=1
> 
> 여기에 따르면 표준어는 쉐이프가 아닌 셰이프라는데, 용어 수정하는 게 좋을까요?

국립국어원은 그러한데 Shapefile 벤더사는 쉐이프파일로 사용하고 있어서요, 이 경우는 벤더사를 따르는게 맞을 것 같아요. 
https://www.esrikr.com/?s=shapefile

2021-12-15 07:59 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +    - [2.5 다운로드](#2.5 다운로드)
반영하였습니다.

2021-12-15 08:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +- Altibase Migration Center 7.9 Release Notes
취소했습니다.

2021-12-15 08:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +    - [5.3 설치](#5.3 설치)
반영하였습니다.

2021-12-15 08:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader는 shapefile 내보내기와 불러오기를 위한 도구로, Java를 기반으로 한 오픈소스 라이브러리인 GeoTools를 사용하여 작성되었다.
넵. 반영하였습니다.

2021-12-16 06:33 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +    - [2.5 다운로드](#2.5 다운로드)
1. 개요 , 2. 릴리즈 정보 도 링크 생성해주세요

2021-12-17 01:49 UTC, eheejung reviewed
마이그레이션 센터 릴리즈 노트 한글 문서 리뷰 다시 올립니다.

2021-12-17 01:49 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| Oracle JDBC Driver         | Homepage: [http://www.oracle.com](http://www.oracle.com/) License: OTN(http://www.oracle.com/technetwork/licenses/distribution-license152002.html) |
License: 는 다음 라인으로 보내주세요. 영문이랑 비교해보면 아실꺼에요.

2021-12-17 01:49 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 순수 Java 기반 클라이언트 애플리케이션으로, 클라이언트의 하드웨어나 OS 대신 JAVA Runtime Environment (JRE)에 의존한다. 단, Migration Center를 GUI 모드로 실행하기 위해 운영 체제의 그래픽 라이브러리에 대한 추가 지원이 필요하다.
클라이언트의 하드웨어나 OS 대신 JAVA Runtime Environment (JRE)에 의존한다.
-> '대신' 보다 '보다' 가 의미가 맞을 것 같아요.

2021-12-17 01:56 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's%20Manual.md
반영했습니다.

2021-12-17 01:56 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/Migration%20Center%20User's%20Manual.md
반영했습니다.

2021-12-17 01:57 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +    - [5.3 설치](#53-설치)
반영했습니다.

2021-12-17 01:58 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +    - [2.5 다운로드](#25-다운로드)
반영했습니다.

2021-12-17 01:58 UTC, eheejung reviewed
마이그레이션 센터 릴리즈 노트 한글에 리뷰 한 개 추가, 
altiShapeLoader 릴리즈 노트 한글에 리뷰 추가했습니다.
확인 부탁드립니다.

2021-12-17 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +쉐이프 파일 가져오기는 좌표 및 좌표 속상과 같은 공간 데이터 정보를 쉐이프 파일로부터 알티베이스 데이터베이스 테이블에 삽입하는 것을 의미한다. 쉐이프 파일 내보내기는 알티베이스 데이터베이스 테이블에 저장된 공간 데이터 정보를 사용하여 쉐이프 파일을 생성하는 것을 의미한다.
좌표 및 좌표 속상과 -> 속성 오타

2021-12-17 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +| Apache log4j         | 2.15.0  | Homepage: https://logging.apache.org/log4j/ License: Apache License 2.0(http://www.apache.org/licenses/LICENSE-2.0.txt) |
License: 부터 다음 줄로 보내주세요. 역시 영문이랑 비교해보면 알거에요.

2021-12-17 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +[https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's%20Manual.md](https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's
\[https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's%20Manual.md] -> \[altiShapeLoader User's Manual\] 변경해주세요.

2021-12-17 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader User's Manual를 참고한다.
를 -> 을

2021-12-17 01:58 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center User's Manual를 참고한다.
를 -> 을

2021-12-17 01:58 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +-----
반영했습니다.

2021-12-17 02:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| Oracle JDBC Driver         | Homepage: [http://www.oracle.com](http://www.oracle.com/) License: OTN(http://www.oracle.com/technetwork/licenses/distribution-license152002.html) |
반영했습니다.

2021-12-17 02:00 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center는 순수 Java 기반 클라이언트 애플리케이션으로, 클라이언트의 하드웨어나 OS 대신 JAVA Runtime Environment (JRE)에 의존한다. 단, Migration Center를 GUI 모드로 실행하기 위해 운영 체제의 그래픽 라이브러리에 대한 추가 지원이 필요하다.
반영했습니다.

2021-12-17 02:01 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +쉐이프 파일 가져오기는 좌표 및 좌표 속상과 같은 공간 데이터 정보를 쉐이프 파일로부터 알티베이스 데이터베이스 테이블에 삽입하는 것을 의미한다. 쉐이프 파일 내보내기는 알티베이스 데이터베이스 테이블에 저장된 공간 데이터 정보를 사용하여 쉐이프 파일을 생성하는 것을 의미한다.
반영했습니다.

2021-12-17 02:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +| Apache log4j         | 2.15.0  | Homepage: https://logging.apache.org/log4j/ License: Apache License 2.0(http://www.apache.org/licenses/LICENSE-2.0.txt) |
반영했습니다.

2021-12-17 02:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +[https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's%20Manual.md](https://github.com/ALTIBASE/Documents/blob/master/Manuals/Tools/kor/altiShapeLoader%20User's
반영했습니다.

2021-12-17 02:02 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_altiShapeLoader_1_0_Release_Notes.md
> +altiShapeLoader User's Manual를 참고한다.
반영했습니다.

2021-12-17 02:03 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +Migration Center User's Manual를 참고한다.
반영했습니다.

2021-12-17 03:12 UTC, eheejung approved these changes
Migration Center, altiShapeLoader 릴리즈 노트 한글 리뷰 마칩니다. 
커밋한 다수 파일 중 일부 파일만 머지해야 할 경우 브랜치를 새로 생성해서 Pull Request 하면 될 것 같습니다.

2021-12-23 02:17 UTC, KwangikAlti approved these changes

2021-12-23 02:25 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_9_Release_Notes.md
> +| CLI mode | Sun of IBM Java 5 or higher | Not required       |
Sun이 Oracle로 인수되었으니 Oracle이 맞는 것 같습니다.

2021-12-23 04:09 UTC, zennken commented
BUG-49499 MigrationCenter log4j 보안 문제로 2.17.0 버전으로 업그레이드 작업으로 인하여 Migration Center 자바환경이 1.5 -> 8 으로 변경되었습니다.

이에 대한 변경이 릴리즈 문서는 업데이트 되었는데, 영문 매뉴얼은 빠졌습니다.

아래 링크 참고하셔서 반영 부탁드립니다. 감사합니다.
https://github.com/ALTIBASE/Documents/pull/141/files

2021-12-23 04:11 UTC, zennken commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +| CONSTRAINT_ID    | INTEGER       | The CHECK constraint identifier                         |
CHECK constraint 가 맞습니다. constriant의 한가지 입니다.

2021-12-23 04:12 UTC, zennken commented
앗 실수로 닫아 버렸네요. 다시 open합니다.

2021-12-23 04:14 UTC, zennken approved these changes

2021-12-23 04:15 UTC, zennken commented
BUG-49499 MigrationCenter log4j 보안 문제로 2.17.0 버전으로 업그레이드 작업으로 인하여 Migration Center 자바환경이 1.5 -> 8 으로 변경되었습니다.

이에 대한 변경이 릴리즈 문서는 업데이트 되었는데, 영문 매뉴얼은 빠졌습니다.

아래 링크 참고하셔서 반영 부탁드립니다. 감사합니다.
https://github.com/ALTIBASE/Documents/pull/141/files

2022-01-05 06:32 UTC, eheejung commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +| CONSTRAINT_ID    | INTEGER       | The CHECK constraint identifier                         |
아, 그렇군요. 
그럼 Admin 매뉴얼 영문에 CHECK Constraints 로 되어있는데 수정해야 할 것 같습니다?

2022-01-05 06:37 UTC, zennken commented on Manuals/Altibase_7.2/eng/General Reference-2.The Data Dictionary.md
> +| CONSTRAINT_ID    | INTEGER       | The CHECK constraint identifier                         |
네...모두 복수형으로 되어 있네요. 단수형으로 바꿔야 할 것 같네요. 타사의 매뉴얼도 같이 참고하면 좋을 것 같습니다.

https://docs.oracle.com/cd/B19306_01/server.102/b14200/clauses002.htm

2022-01-13 06:04 UTC, eheejung reviewed
다시 리뷰 시작하며 보다보니...변경 파일에 7.1 영문, 7.1 한글, 7.1 pdf 섞여 있습니다.
7.2 영문 매뉴얼 리뷰이면 그에 맞는 파일만 커밋해서 PR 해주시는 게 좋겠습니다. 
확인 부탁드려요.

2022-03-07 03:39 UTC, eheejung reviewed
이 브랜치 사용하지 않으면 PR 종료하고 브랜치 삭제해주세요.

2022-03-07 03:40 UTC, eheejung commented
> 이 브랜치 사용하지 않으면 PR 종료하고 브랜치 삭제해주세요.

아 ALTIBASE 브랜치가 아니라 브랜치 삭제는 무시하시고 PR만 종료해주세요.

2022-04-19 01:05 UTC, closed without merging