Altibase_dataCompJ_7_2_Release_Notes.md 한글화
ALTIBASE/Documents pull request #179
Opened 2022-02-22 10:05 UTC by haeinnmin

리뷰 부탁드립니다.

2022-02-22 22:25 UTC, zennken requested changes
매뉴얼 참고하셔서 용어 및 표현을 맞추는 것이 좋을 것 같습니다.

2022-02-22 22:25 UTC, zennken commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 순수 Java 기반 클라이언트 애플리케이션으로, 클라이언트의 하드웨어나 OS보다 JAVA Runtime Environment (JRE)에 의존한다.
", 클라이언트의" -> 생략하는 게 더 자연스러워 보입니다.

2022-02-22 22:25 UTC, zennken commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- 디스크: 설치를 위해 최소 500MB 이상의 여유 공간 필요
"설치를 위해 " 생략해도 무방해 보입니다.

2022-02-22 22:25 UTC, zennken commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 두 이종 데이터베이스간 데이터 불일치를 해소하여 데이터 일관성을 보장하기 위해 설계된 도구이다. dataCompj에서 비교를 하는 메인 대상 데이터는 Altibase에서 제공하는 Altibase Adapter for Oracle(oraAdapter) 또는 JDBC Adapter를 사용하여 Altibase에서 다른 이종
1. dataCompj -> dataCompJ 로 변경해야 합니다.
2. 번역이 너무 딱딱합니다. 아래 매뉴얼 참고하셔서 용어와 표현에 일관성을 갖추는 게 좋을 것으로 판단됩니다. 
https://github.com/ALTIBASE/Documents/blob/master/Manuals/Altibase_7.1/kor/Utilities%20Manual.md#3datacompj

2022-02-23 04:03 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- 디스크: 설치를 위해 최소 500MB 이상의 여유 공간 필요
수정했습니다.

2022-02-23 04:03 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 순수 Java 기반 클라이언트 애플리케이션으로, 클라이언트의 하드웨어나 OS보다 JAVA Runtime Environment (JRE)에 의존한다.
수정했습니다.

2022-02-23 05:03 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 두 이종 데이터베이스간 데이터 불일치를 해소하여 데이터 일관성을 보장하기 위해 설계된 도구이다. dataCompj에서 비교를 하는 메인 대상 데이터는 Altibase에서 제공하는 Altibase Adapter for Oracle(oraAdapter) 또는 JDBC Adapter를 사용하여 Altibase에서 다른 이종
수정하였습니다.

2022-02-23 05:45 UTC, zennken requested changes

2022-02-23 05:45 UTC, zennken commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 Altibase 데이터베이스에서 이기종 데이터베이스로 데이터를 복제한 이후, 데이터 정합성 확인과 데이터 불일치를 해소하기 위한 도구이다. dataCompJ는 비교하는 메인 대상 데이터를 Altibase에서 제공하는 Altibase Adapter for Oracle(oraAdapter) 또는 JDBC Adapter를 사
dataCompJ는 비교하는 메인 대상 데이터를 Altibase에서 제공하는 Altibase Adapter for Oracle(oraAdapter) 또는 JDBC Adapter를 사용하여 Altibase에서 다른 이기종 데이터베이스로 복제한다.
-> dataCompJ는
데이터 복제 툴로써 Altibase에서 제공하는 Altibase Adapter for Oracle (이하
oraAdapter) 또는 Altibase Adapter for JDBC(이하 jdbcAdapter)를 사용하는 것을
전제한다.

dataCompJ는 Altibase와 다른 이기종 데이터베이스를 테이블 단위로 비교하고 데이터 불일치가 있는 경우 이에 관한 정보를 파일로 출력한다.
-> 이 문장 뒤에 "불일치 데이터를 Slave 데이터베이스에 직접 적용하여 데이터를
일치시키는 기능 또한 제공한다."를 추가해야 할 것 같습니다.

Altibase dataCompJ의 올바른 사용은 뛰어난 기술적 성능을 통해 효과적인 데이터베이스 관리를 가능하게 한다.
-> "dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다." 내용이 어떨까 합니다. 기계적인 번역을 넘어 의미를 함께 부여해야 고객에게 정확한 내용을 전달할 수 있을 것 같습니다.

2022-02-23 05:54 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 Altibase 데이터베이스에서 이기종 데이터베이스로 데이터를 복제한 이후, 데이터 정합성 확인과 데이터 불일치를 해소하기 위한 도구이다. dataCompJ는 비교하는 메인 대상 데이터를 Altibase에서 제공하는 Altibase Adapter for Oracle(oraAdapter) 또는 JDBC Adapter를 사
반영하였습니다.

2022-02-23 05:57 UTC, zennken approved these changes
수고하셨습니다. 한글 표현 다듬는 작업은 희정님께 부탁드립니다.

2022-02-23 06:47 UTC, KwangikAlti approved these changes

2022-02-25 07:24 UTC, haeinnmin commented
@eheejung 희정님, 리뷰 부탁드립니다~

2022-02-25 07:26 UTC, eheejung reviewed
급한 업무를 끝내지 못해서 확인 못하고 있습니다. 최대한 빨리 리뷰하겠습니다.

2022-03-03 02:46 UTC, eheejung reviewed
리뷰 남깁니다. 늦어서 죄송합니다.

2022-03-03 02:46 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다.
불필요한 단어를 삭제하고 문장 순서를 변경해봤습니다. 

```suggestion
dataCompJ는 Altibase 데이터베이스에서 이기종 데이터베이스로 복제한 데이터를 대상으로 데이터 정합성 확인과 데이터 불일치를 해소하기 위한 도구이다. 테이블 단위로 데이터를 비교하고 데이터 불일치가 있는 경우 이에 관한 정보를 파일로 출력한다. 불일치 데이터를 Slave 데이터베이스에 직접 적용하여 데이터를 일치시키는 기능도 제공한다.
dataCompJ가 관리하는 데이터는 데이터 복제 도구로 Altibase에서 제공하는 Adapter for Oracle (이하 oraAdapter) 또는 Adapter for JDBC(이하 jdbcAdapter)를 사용하여 복제한 데이터를 전제로 한다. 
dataCompJ는 편리한 사용성과 빠른 성능으로, 효율적인 이기종 데이터베이스 간 데이터 관리 방법을 제공한다.
```

2022-03-03 02:46 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| dataCompJ7.2.zip<br/>dataCompJ7.2.tar.gz |
이 부분을 꼭 표로 할 필요가 있을까 싶어요. 점 목록으로 해도 되지 않을까 싶습니다. 

```suggestion
2가지 종류의 압축 파일을 제공한다. 
- dataCompJ7.2.zip
- dataCompJ7.2.tar.gz 
```

2022-03-03 02:55 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다.
@zennken 제가 수정한 2번째 문장 의미가 원래 의도와 같은지 검토 부탁드립니다. 

as-is
dataCompJ는
데이터 복제 툴로써 Altibase에서 제공하는 Altibase Adapter for Oracle (이하 oraAdapter) 또는 Altibase Adapter for JDBC(이하 jdbcAdapter)를 사용하는 것을 전제한다.

to-be
dataCompJ가 관리하는 데이터는 데이터 복제 도구로 Altibase에서 제공하는 Adapter for Oracle 또는 Adapter for JDBC를 사용하여 복제한 데이터를 전제로 한다.

2022-03-03 03:50 UTC, zennken commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다.
@eheejung 희정님, 원래 의도와 일치합니다. 이렇게 써둔 이유는 고객이 이기종 데이터베이스간 임의의 데이터 타입으로 매핑한 경우가 있어, 알티베이스 Adapter에서 제공하는 호환 데이터 타입으로 한정하기 위한 것입니다.

2022-03-03 05:04 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다.
> @eheejung 희정님, 원래 의도와 일치합니다. 이렇게 써둔 이유는 고객이 이기종 데이터베이스간 임의의 데이터 타입으로 매핑한 경우가 있어, 알티베이스 Adapter에서 제공하는 호환 데이터 타입으로 한정하기 위한 것입니다.

확인 감사합니다~~

2022-03-03 10:03 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +Altibase dataCompJ는 편리한 사용성과 빠른 성능으로 효율적인 이기종 데이터베이스간 데이터 관리 방법을 제공한다.
반영하였습니다.

2022-03-03 10:04 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| dataCompJ7.2.zip<br/>dataCompJ7.2.tar.gz |
반영하였습니다.

2022-03-03 12:52 UTC, eheejung reviewed
추가 리뷰 남깁니다.

2022-03-03 12:52 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 편리한 사용성과 빠른 성능으로, 효율적인 이기종 데이터베이스 간 데이터 관리 방법을 제공한다.
웹으로 보면 라인 구분이 안 되어 있습니다. 아래와 같이 문장 구분하면 좋겠습니다. 

dataCompJ는 ~ 일치시키는 기능도 제공한다.
dataCompJ가 관리하는 ~ 전제로 한다. 
dataCompJ는 ~ 데이터 관리 방법을 제공한다.

2022-03-03 12:52 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- N/A
N/A 삭제해도 되지 않을까 싶습니다.

2022-03-03 12:52 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| PK        | Synopsis                                                     |
한글로 바꾸면 좋겠군요. 

```suggestion
| 버그 번호        | 제목                                                     |
```

2022-03-03 12:52 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- Altibase: Altibase 5.3.3 이상 버전
```suggestion
- Altibase: Altibase 5.3.3 이상
```

2022-03-04 04:30 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 편리한 사용성과 빠른 성능으로, 효율적인 이기종 데이터베이스 간 데이터 관리 방법을 제공한다.
반영했습니다.

2022-03-04 04:31 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- N/A
반영했습니다.

2022-03-04 04:44 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| PK        | Synopsis                                                     |
바로 아래에 라이브러리 / 오픈소스 라이선스 부분도 국문으로 변경할까요?
다른 릴리즈 노트 파일들을 확인하였는데 표의 머리글 행(ex. 버그 번호, 제목)이 영어로 되어 있는 경우가 있는데 같이 수정해야 할까요?

2022-03-04 04:45 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +- Altibase: Altibase 5.3.3 이상 버전
반영했습니다.

2022-03-07 00:55 UTC, eheejung approved these changes
리뷰 마칩니다. 수고하셨습니다.

2022-03-10 01:20 UTC, eheejung commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| PK        | Synopsis                                                     |
> 바로 아래에 라이브러리 / 오픈소스 라이선스 부분도 국문으로 변경할까요? 다른 릴리즈 노트 파일들을 확인하였는데 표의 머리글 행(ex. 버그 번호, 제목)이 영어로 되어 있는 경우가 있는데 같이 수정해야 할까요?

저는, 크게 중요하지는 않아도.. 라이브러리 / 오픈소스 라이선스 부분도 국문으로 변경하자는 의견입니다. 

이미 릴리즈 한 릴리즈 노트는 그대로 두고 이후부터 반영하면 될 것 같습니다.

2022-03-10 08:44 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +| PK        | Synopsis                                                     |
국문으로 수정하였습니다.

2022-03-14 05:07 UTC, merged

2022-03-14 05:08 UTC, haeinnmin commented
충헌님, 머지가 늦어 죄송합니다. 머지 완료합니다.

2022-03-14 05:40 UTC, scott-altibase reviewed
리뷰 남깁니다. 확인 부탁드립니다

2022-03-14 05:40 UTC, scott-altibase commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 Altibase 데이터베이스에서 이기종 데이터베이스로 복제한 데이터를 대상으로 데이터 정합성 확인과 데이터 불일치를 해소하기 위한 도구이다. 테이블 단위로 데이터를 비교하고 데이터 불일치가 있는 경우 이에 관한 정보를 파일로 출력한다. 불일치 데이터를 Slave 데이터베이스에 직접 적용하여 데이터를 일치시키는 기능도 제공한다.<br>
Altibase 데이터베이스에서-> Altibase에서 로 하는게 더 자연스럽습니다.
다른 곳에서도 그냥 Altibase라고만 사용되고 있습니다.

2022-03-14 08:27 UTC, haeinnmin commented on ReleaseNotes/kor/Altibase_dataCompJ_7_2_Release_Notes.md
> +dataCompJ는 Altibase 데이터베이스에서 이기종 데이터베이스로 복제한 데이터를 대상으로 데이터 정합성 확인과 데이터 불일치를 해소하기 위한 도구이다. 테이블 단위로 데이터를 비교하고 데이터 불일치가 있는 경우 이에 관한 정보를 파일로 출력한다. 불일치 데이터를 Slave 데이터베이스에 직접 적용하여 데이터를 일치시키는 기능도 제공한다.<br>
간단한 사항이라 마스터 브랜치에서 바로 수정하도록 하겠습니다.

2022-03-14 08:47 UTC, scott-altibase reviewed
수고하셨습니다