BUG-49692
ALTIBASE/Documents pull request #217
Opened 2022-04-22 05:53 UTC by haeinnmin

7.2 릴리즈 노트 재확인 중 영문 매뉴얼에 누락된 부분이 발견되어 추가합니다.
리뷰 요청드립니다.

2022-05-02 09:31 UTC, eheejung reviewed
리뷰 남깁니다.

2022-05-02 09:31 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### reuse_resultset
7.1, trunk 영문 매뉴얼에도 추가해주세요.

2022-05-02 09:31 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### getprocedures_return_functions
7.1, trunk 영문 매뉴얼에도 추가해주세요.

2022-05-02 09:31 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### getcolumns_return_jdbctype
7.1, trunk 영문 매뉴얼에도 추가해주세요.

2022-05-02 09:31 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### batch_setbytes_use_lob
7.1, trunk 영문 매뉴얼에도 추가해주세요.

2022-05-03 04:54 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Defualt Value | true                                                         |
수정했습니다.

2022-05-03 04:55 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### reuse_resultset
국문 매뉴얼 업데이트에 맞춰 7.2에 먼저 영문 업데이트하고 피드백받은 후에 추가하겠습니다.

2022-05-03 04:57 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
먼저 생성한 ResultSet 객체에 close() 메소드를 사용하면 다음 생성한 ResultSet 객체에 영향을 준다.

이 부분에서 어떤 영향을 의미하는지 설명해주실 수 있나요?

2022-05-03 04:57 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### getprocedures_return_functions
국문 매뉴얼 업데이트에 맞춰 7.2에 먼저 영문 업데이트하고 피드백받은 후에 추가하겠습니다.

2022-05-03 04:58 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Defualt Value | true                                                         |
수정했습니다.

2022-05-03 04:58 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Utilities Manual.md
> +This specifies the number of changed data(INSERT, DELETE or UPDATE) to be committed at once. The default value is 1000.
국문 매뉴얼 업데이트에 맞춰 7.2에 먼저 영문 업데이트하고 피드백받은 후에 추가하겠습니다.

2022-05-03 04:58 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### reuse_resultset
국문 매뉴얼 업데이트에 맞춰 7.2에 먼저 영문 업데이트하고 피드백받은 후에 추가하겠습니다.

2022-05-03 04:58 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### getprocedures_return_functions
국문 매뉴얼 업데이트에 맞춰 7.2에 먼저 영문 업데이트하고 피드백받은 후에 추가하겠습니다.

2022-05-03 04:59 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
먼저 생성한 ResultSet 객체에 close() 메소드를 사용하면 다음 생성한 ResultSet 객체에 영향을 준다.

이 부분에서 어떤 영향을 의미하는지 설명해주실 수 있나요?

2022-05-03 06:51 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Specifies whether to include function objects in the result of DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns(). When this value is set to false, DatabaseMet
DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns() 메소드가 반환하는 결과에 저장 함수를 포함할지 설정한다.
true는 저장 함수를 포함한다. false는 저장 함수를 포함하지 않으므로 저장 함수 정보를 얻으려면 DatabaseMetaData.getFunctions()와 DatabaseMetaData.getFunctionColumns()를 사용해야 한다.

이렇게는 어떠신가요?

2022-05-03 06:57 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/Utilities Manual.md
> +This specifies the number of changed data(INSERT, DELETE or UPDATE) to be committed at once. The default value is 1000.
반영했습니다.

2022-05-03 06:58 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### batch_setbytes_use_lob
반영했습니다.

2022-05-03 06:59 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### getcolumns_return_jdbctype
반영했습니다.

2022-05-03 07:12 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Specifies whether to include function objects in the result of DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns(). When this value is set to false, DatabaseMet
> DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns() 메소드가 반환하는 결과에 저장 함수를 포함할지 설정한다. true는 저장 함수를 포함한다. false는 저장 함수를 포함하지 않으므로 저장 함수 정보를 얻으려면 DatabaseMetaData.getFunctions()와 DatabaseMetaData.getFunctionColumns()를 사용해야 한다.
> 
> 이렇게는 어떠신가요?

좋습니다.

2022-05-03 22:44 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Specifies whether to include function objects in the result of DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns(). When this value is set to false, DatabaseMet
해당 내용을 7.1과 trunk에도 반영하려다 보니 7.1에 아래 내용이 작성되어 있고 http://nok.altibase.com/pages/viewpage.action?pageId=66459579에서도 확인하였습니다. 포함할까요?

원문) JDBC spec. 4.2를 지원하는 Altibase42.jar 에서만 효과가 있으며 Altibase.jar에서는 설정해도 효과가 없다.
수정안) JDBC 4.2를 지원하는 Altibase42.jar에서만 유효한 프로퍼티이다.

2022-05-03 23:39 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
동일한 PreparedStatement 객체에서 executeQuery 메소드를 사용하여 ResultSet 객체를 여러 번 생성한 경우 첫번째 ResultSet 객체를 재사용할 것인지 설정한다. true는 ResultSet 객체를 재사용하므로 먼저 생성한 ResultSet 객체에 close() 메소드를 사용하면 자원이 해제되어 다음 생성한 ResultSet 객체에 메소드 사용 시 오류가 발생한다. 이를 방지하려면 먼저 생성한 ResultSet 객체의 자원을 해제하고 다음 ResultSet 객체를 생성해야 한다. false는 ResultSet 객체를 재사용하지 않는다.

2022-05-04 09:47 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
> 
약간 변경해봤습니다. 

동일한 PreparedStatement 객체에서 executeQuery 메소드를 사용하여 ResultSet 객체를 여러 번 생성한 경우 첫 번째 ResultSet 객체를 재사용할 것인지 설정한다. true는 ResultSet 객체를 재사용한다. 먼저 생성한 ResultSet 객체에 close() 메소드를 사용하면 자원이 해제되어 다른 ResultSet 객체 사용 시 오류가 발생한다. 이를 방지하려면 먼저 생성한 ResultSet 객체의 자원을 해제하고 다음 ResultSet 객체를 생성해야 한다. false는 ResultSet 객체를 재사용하지 않는다.

2022-05-04 09:56 UTC, eheejung commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Specifies whether to include function objects in the result of DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns(). When this value is set to false, DatabaseMet
> JDBC spec. 4.2를 지원하는 Altibase42.jar

7.1 에는 
JDBC spec. 4.2를 지원하는 Altibase42.jar 와 JDBC spec 3.0을 지원하는 Altibase.jar 를 같이 제공해서 매뉴얼이 다르게 기재된 것입니다. 

trunk와 7.2은 불필요한 내용입니다.

2022-05-06 00:42 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
이대로 반영하겠습니다.

2022-05-06 00:44 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Specifies whether to include function objects in the result of DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns(). When this value is set to false, DatabaseMet
네~ 포함하지 않겠습니다. 감사합니다.

2022-05-06 01:08 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +##### reuse_resultset
반영했습니다.

2022-05-06 01:44 UTC, haeinnmin commented on Manuals/Altibase_7.2/eng/JDBC User's Manual.md
> +| Description   | Speicifies whether to reuse the ResultSet when executeQuery() is executed from the same PreparedStatement. |
7.1의 경우 기본값이 false, trunk는 true인데 7.2는 어떻게 해야 하는지 개발자님께 여쭤보면 되나요?

2022-05-19 00:49 UTC, haeinnmin commented
@scott-altibase 실장님, 리뷰 부탁드립니다

2022-05-24 00:32 UTC, scott-altibase requested changes

2022-05-24 00:32 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/JDBC User's Manual.md
> +| 설명      | DatabaseMetaData.getProcedures(), DatabaseMetaData.getProcedureColumns() 메소드 반환 결과에 저장 함수를 포함할지 설정한다.<br/>true는 저장 함수를 포함한다. false는 저장 함수를 포함하지 않는다. 저장 함수 정보를 얻으려면 DatabaseMetaData.getFun
메소드 반환 결과에 저장 함수를 포함할지 설정한다.
-> 메소드 반환 결과에 저장 함수의 포함 여부를 설정한다

2022-05-24 00:32 UTC, scott-altibase commented on Manuals/Altibase_7.2/kor/JDBC User's Manual.md
> +| 설명      | 동일한 PreparedStatement 객체에서 executeQuery() 메소드를 사용하여 ResultSet 객체를 여러 번 생성한 경우 첫 번째 ResultSet 객체를 재사용할 것인지 설정한다. true는 ResultSet 객체를 재사용한다. 먼저 생성한 ResultSet 객체에 close() 메소드를 사용하면 자원이 해제되어
첫 번째 ResultSet 객체를 재사용할 것인지 설정한다.
-> 첫 번째 ResultSet 객체의 재사용 여부를 설정한다

2022-05-30 08:41 UTC, eheejung commented
전형진 실장님 의견 괜찮은 것 같은데 반영하고 리뷰 다시 요청해주세요~

2022-05-30 22:54 UTC, haeinnmin commented
> 전형진 실장님 의견 괜찮은 것 같은데 반영하고 리뷰 다시 요청해주세요~

반영하여 리뷰 re-request 합니다

2022-05-31 01:39 UTC, eheejung approved these changes
리뷰 마치겠습니다. 수고하셨습니다.

2022-05-31 01:51 UTC, scott-altibase approved these changes
리뷰 마칩니다

2022-05-31 02:06 UTC, merged

2022-05-31 02:06 UTC, haeinnmin commented
머지하고 브랜치 삭제합니다.