Add exception handing for BEFORE UPDATE TRIGGER
ALTIBASE/Documents pull request #228
Opened 2022-05-24 08:46 UTC by eheejung

Add exception handing for BEFORE UPDATE TRIGGER

2022-05-24 22:39 UTC, haeinnmin approved these changes
리뷰 어프루브합니다. 실장님께서도 어프루브하시면 영문 진행하겠습니다.

2022-05-25 00:53 UTC, scott-altibase requested changes

2022-05-25 00:53 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +  UPDATE 트리거 이벤트에 OF 절을 사용할 경우 OF 절에 명시된 컬럼이 변경될 경우에만 트리거를 동작시킨다. LOB 칼럼이 있는 테이블의 경우 'BEFORE UPDATE ... FOR EACH ROW' 구문으로 트리거를 생성할 수는 있으나, 트리거의 동작을 유발하는 DML문이 실행될 때 오류가 발생한다.
DATE 트리거 이벤트에 OF 절을 사용할 경우 OF 절에 명시된 컬럼이 변경될 경우에만 트리거를 동작시킨다
경우가 반복 사용되어 어감이 어색하고 의미 전달이 헷갈릴 수 있습니다. 다음과 같이 바꿔 봤습니다.
UPDATE 트리거 이벤트와 함께 사용된  OF절의 컬럼이 변경될 경우에만 트리거를 동작시킨다.

아래 문장도 경우를 삭제했습니다.
LOB 칼럼이 있는 테이블의 경우 'BEFORE UPDATE... -> LOB 칼럼이 있는 테이블은 'BEFORE UPDATE..

2022-05-25 01:39 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +  UPDATE 트리거 이벤트에 OF 절을 사용할 경우 OF 절에 명시된 컬럼이 변경될 경우에만 트리거를 동작시킨다. LOB 칼럼이 있는 테이블의 경우 'BEFORE UPDATE ... FOR EACH ROW' 구문으로 트리거를 생성할 수는 있으나, 트리거의 동작을 유발하는 DML문이 실행될 때 오류가 발생한다.
> "UPDATE 트리거 이벤트에 OF 절을 사용할 경우"는 내용 상 꼭 필요한 부분입니다. 삭제하면 전체 의미가 달립니다. 

그래서 경우만 삭제하고자 합니다. 

```suggestion
UPDATE 트리거 이벤트에 OF 절을 사용하면 OF 절에 명시된 컬럼이 변경될 경우에만 트리거를 동작시킨다. LOB 칼럼이 있는 테이블은 'BEFORE UPDATE ... FOR EACH ROW' 구문으로 트리거를 생성할 수는 있으나, 트리거의 동작을 유발하는 DML문이 실행될 때 오류가 발생한다.
```

2022-05-25 04:07 UTC, haeinnmin approved these changes
어프루브합니다. 영문 진행하겠습니다.

2022-05-25 04:20 UTC, eheejung commented
> 어프루브합니다. 영문 진행하겠습니다.

대기해주세요. 
QA팀 내 리뷰 완료 후 개발자에게 최종 리뷰 받고 영문 진행하려고 합니다.

2022-05-25 04:25 UTC, haeinnmin commented
> > 어프루브합니다. 영문 진행하겠습니다.
> 
> 대기해주세요. QA팀 내 리뷰 완료 후 개발자에게 최종 리뷰 받고 영문 진행하려고 합니다.

푸시 후에 희정님 메시지를 봐서 revert하였습니다. 푸시 전 확인했어야 하는데 죄송합니다.

2022-05-26 07:28 UTC, eheejung commented
@scott-altibase 실장님, 리뷰 반영한 것 검토 부탁드립니다.

2022-05-27 04:14 UTC, scott-altibase approved these changes
리뷰 완료 합니다

2022-05-27 04:15 UTC, eheejung commented
하영님, 매뉴얼 최종 반영 결과 리뷰 부탁드립니다.

2022-05-27 04:44 UTC, altihykim commented
확인했습니다. 고생하셨습니다^^

2022-05-27 04:47 UTC, altihykim approved these changes

2022-05-27 05:29 UTC, haeinnmin commented
@eheejung 희정님께서 브랜치를 생성하셔서 리뷰 요청을 할 수가 없네요... 영문 변환했습니다. 리뷰 부탁드립니다~

2022-05-27 08:02 UTC, eheejung reviewed
리뷰 남깁니다.

2022-05-29 22:14 UTC, haeinnmin commented on Manuals/Altibase_7.1/eng/SQL Reference.md
> +  INSERT option is used to fire the trigger when data are inserted into the table by executing an INSERT statement. If the table has a LOB column, a trigger can be created with the ‘BEFORE INSERT … F
모두 의미상 문제는 없을 것 같지만 희정님께서 말씀하신 것으로 수정하겠습니다~

2022-05-29 22:19 UTC, haeinnmin commented on Manuals/Altibase_7.1/eng/SQL Reference.md
> +  UPDATE option is used to fire the trigger when data in the table are updated by executing an UPDATE statement. The optional OF clause further specifies that the trigger will fire only when an UPDAT
수정했습니다

2022-05-30 08:42 UTC, eheejung commented on Manuals/Altibase_7.1/eng/SQL Reference.md
> +  INSERT option is used to fire the trigger when data are inserted into the table by executing an INSERT statement. If the table has a LOB column, a trigger can be created with the ‘BEFORE INSERT … F
> 모두 의미상 문제는 없을 것 같지만 희정님께서 말씀하신 것으로 수정하겠습니다~

ㅋ 영어가 짧아서... 반영해주셔서 감사합니다~

2022-05-30 08:43 UTC, eheejung commented
@scott-altibase 전형진 실장님 리뷰 후 승인 부탁드립니다~

2022-06-02 07:46 UTC, merged

2022-06-02 07:47 UTC, eheejung commented
실장님 승인 기다리지 못하고 머지했습니다.