BUG-49828 Add IPC_SHM_KEY, IPC_SEM_KEY, IPCDA_SHM_KEY, IPCDA_SEM_KEY
ALTIBASE/Documents pull request #271
Opened 2022-08-09 02:09 UTC by eheejung

매뉴얼에 추가되는 내용입니다. 
개발자 초안을 QA팀에서 변경하고 수정본에 대해 리뷰합니다.

2022-08-09 10:18 UTC, eheejung commented
@colehaanlee 상훈님, 초안에서 업데이트 했습니다. 리뷰 부탁드립니다.

2022-08-10 07:59 UTC, colehaanlee commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널을 생성하는 데 필요한 세마포어 키(key)를 사용자가 정의한 값으로 설정하는 프로퍼티이다.
윈도우 플랫폼에서는 지원하지 않는다는 불필요해서 제거하신건가요?

2022-08-10 08:01 UTC, eheejung commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널을 생성하는 데 필요한 세마포어 키(key)를 사용자가 정의한 값으로 설정하는 프로퍼티이다.
> 윈도우 플랫폼에서는 지원하지 않는다는 불필요해서 제거하신건가요?

아, [BUG-49828](https://altra.altibase.com/altimis-2.0/app_bug_new/bug_view.jsp?pk=49828) 버그에 기록했는데, 
Altibase  6.3.1, 6.5.1 매뉴얼은 유지보수하고 있지 않고, Altibase 7.1 이상에서 윈도우즈 서버를 지원하지 않으므로 윈도우즈 내용은 추가하지 않았습니다.

2022-08-10 08:02 UTC, colehaanlee commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널을 생성하는 데 필요한 세마포어 키(key)를 사용자가 정의한 값으로 설정하는 프로퍼티이다.
그렇군요 알겠습니다.

2022-08-10 08:04 UTC, colehaanlee commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널을 생성하는 데 필요한 세마포어 키(key)를 사용자가 정의한 값으로 설정하는 프로퍼티이다.
네 알겠습니다~

2022-08-16 01:11 UTC, eheejung commented
@scott-altibase 실장님, 새롭게 추가되는 내용이라 리뷰 부탁드립니다.

2022-08-16 06:23 UTC, scott-altibase requested changes
코멘트 남겼습니다

2022-08-16 06:23 UTC, scott-altibase commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널은 Altibase 서버 구동 시 생성되는데, 공유 메모리 키 사용 중이거나 다른 이유로 공유 메모리를 생성하지 못하면 Altibase 서버 구동은 실패한다. 이 경우 Altibase 서버 트레이스 로그 altibase_boot.log에서 시스템 에러(errno)를 확인하고 그에 따른 적절한 처리를 해야 한다.
공유 메모리 키 사용 중이거나 다른 이유로 공유 메모리를 생성하지 못하면
-> 공유 메모리 키가 사용 중이거나 다른 이유로 공유 메모리를 생성하지 못하면

2022-08-16 06:46 UTC, eheejung commented on Manuals/Altibase_trunk/kor/General_Reference-1.Data Types & Altibase Properties.md
> +IPC 채널은 Altibase 서버 구동 시 생성되는데, 공유 메모리 키 사용 중이거나 다른 이유로 공유 메모리를 생성하지 못하면 Altibase 서버 구동은 실패한다. 이 경우 Altibase 서버 트레이스 로그 altibase_boot.log에서 시스템 에러(errno)를 확인하고 그에 따른 적절한 처리를 해야 한다.
감사합니다~ 수정하고 머지하겠습니다.

2022-08-16 07:04 UTC, scott-altibase approved these changes
수고하셨습니다

2022-08-16 08:17 UTC, merged