Bug 49904 replication sender ip를 공식 기능으로 제공합니다
ALTIBASE/Documents pull request #279
Opened 2022-08-28 23:47 UTC by lswhh

bug-49904 리뷰 요청 드립니다.

2022-08-29 07:48 UTC, scott-altibase requested changes

2022-08-29 07:48 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +프로퍼티에 입력된 IP를 처음부터 ROUND-ROBIN(돌아가면서)으로 선택해서 센더 소켓 지역 IP에 사용 함.
위에서는 다중값으로 설정된 경우 설정된 순서대로 송신자 통신소켓에 지역 IP를 할당 한다고 되어 있는데
ROUND-ROBIN으로 선택 하는 것과는 의미가 좀 다른것 같습니다.
프로퍼티에 입력된 IP를 처음부터 ROUND-ROBIN(돌아가면서)으로 선택해서 센더 소켓 지역 IP에 사용 함
-> 프로퍼티에 입력된 IP를 설정된 순서대로 선택해서 센더 소켓 지역 IP에 사용 함

2022-08-29 07:48 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +서버 프로퍼티임으로 모든 이중화 객체에서 동일한 순서로 REPLICATION_SENDER_IP 값을 사용한다.
서버 프로퍼티임으로
-> 서버 프로퍼티이므로

2022-08-29 07:48 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +* 주의사항: REPLICATION_SENDER_IP의 설정에 따라 이중화 Sender가 접속 실패 후 재접속 될 수 있다. (실패 시 에러메시지 altibase_rp.log 에 출력 후 다음 REPLICATION_SENDER_IP로 자동 재시도)
(실패 시 에러메시지 altibase_rp.log 에 출력 후 다음 REPLICATION_SENDER_IP로 자동 재시도)
-> (실패 시 에러메시지를 altibase_rp.log 에 출력 후 다음 REPLICATION_SENDER_IP로 자동으로 재시도 한다)

2022-08-31 10:14 UTC, eheejung commented
죄송합니다. 이제 메일을 확인했습니다...;;; 내일 리뷰 마치겠습니다!!

2022-09-01 00:26 UTC, scott-altibase reviewed
코멘트 남겼습니다

2022-09-02 05:12 UTC, eheejung commented
초안 수정해서 올렸습니다. 
@scott-altibase 번거로우시겠지만 다시 리뷰 부탁드립니다. 
@lswhh 이승원 팀장님도 리뷰 부탁드립니다..

변경 사항

- 프로퍼티 매뉴얼에 REPLICATION_SENDER_IP 위치 변경했습니다. 알파벳 순으로.
- 예제의 IP 주소를 망 분리 시 사용하는 일반적인 형태의 IP 주소로 변경했습니다.
- 예제에서 V$REPRECEIVER 조회 결과를 삭제했습니다. V$REPSENDER.PEER_IP 로 원격 서버 IP 알 수 있어서 불필요하다고 판단했습니다. 혹 다른 의도가 있어서 추가한 것이면, 말씀해주시면 다시 추가하겠습니다. 
- 예제에서 B 서버의 이중화 송신자/수신자 정보 삭제했습니다. A 서버와 같은 내용이라 한 곳만 보여줘도 충분하다고 판단했습니다. 혹 다른 의도가 있어서 추가한 것이면, 말씀해주시면 다시 추가하겠습니다. 
- 링크는 master 브랜치 경로를 입력해서 안 열리는 것이 맞습니다.

2022-09-02 06:35 UTC, lswhh commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +  REPLICATION_SENDER_IP 값으로 호스트네임을 입력하면 이중화 시작이 실패한 상태로 Altibase 서버가 구동된다.
여기는, 만약 REPLICATION_SENDER_AUTO_START가 1로 되어있는 경우 서버가 뜨면서 SENDER가 시작 실패하면 서버가 구동이 안될것 같은데.. 실제로 구동이 되었나요? 
버그에 테스트 한 내역은 이중화를 나중에 따로 시작 시키신거 아닌지요? 
확인 부탁드립니다.

2022-09-02 06:39 UTC, eheejung commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +  REPLICATION_SENDER_IP 값으로 호스트네임을 입력하면 이중화 시작이 실패한 상태로 Altibase 서버가 구동된다.
> 여기는, 만약 REPLICATION_SENDER_AUTO_START가 1로 되어있는 경우 서버가 뜨면서 SENDER가 시작 실패하면 서버가 구동이 안될것 같은데.. 실제로 구동이 되었나요? 버그에 테스트 한 내역은 이중화를 나중에 따로 시작 시키신거 아닌지요? 확인 부탁드립니다.

네. REPLICATION_SENDER_AUTO_START=1 이고 Altibase 서버가 정상적으로 구동되었습니다. 
이중화 객체가 2개이고 프로퍼티 설정은 아래와 같이 했는데, 이중화 객체 1개는 시작, 1개는 실패했습니다. 
REPLICATION_SENDER_IP=localhost -> hostname, 20.0.0.1 로 연결 안 되는 이중화 객체는 실패
REPLICATION_SENDER_IP=20.0.0.1   -> 이걸로 연결되는 이중화 객체는 성공

2022-09-02 06:45 UTC, eheejung commented on Manuals/Altibase_7.1/kor/Replication Manual.md
> +  REPLICATION_SENDER_IP 값으로 호스트네임을 입력하면 이중화 시작이 실패한 상태로 Altibase 서버가 구동된다.
> 여기는, 만약 REPLICATION_SENDER_AUTO_START가 1로 되어있는 경우 서버가 뜨면서 SENDER가 시작 실패하면 서버가 구동이 안될것 같은데.. 실제로 구동이 되었나요? 버그에 테스트 한 내역은 이중화를 나중에 따로 시작 시키신거 아닌지요? 확인 부탁드립니다.

이중화 객체 한 개로도 해봤는데 이중화 시작은 실패한 채로 Altibase 서버는 정상 구동됩니다.

2022-09-05 06:11 UTC, eheejung commented
@lswhh 이승원 팀장님, 다른 부분은 리뷰 끝나셨을까요?

2022-09-05 06:13 UTC, eheejung commented
@scott-altibase 초안 수정해서 올렸습니다. 번거로우시겠지만 다시 리뷰 부탁드립니다.

2022-09-06 00:03 UTC, lswhh commented
다른 부분은 리뷰 완료 하였는데, 
"bug-49924 REPLICATION_SENDER_IP가 hostname일때 서버 시작이 실패해야합니다." 버그 등록하였습니다. 
이 부분에 대해서 좀 더 논의해 보고 의견 드리겠습니다.

2022-09-06 00:24 UTC, eheejung commented
> 다른 부분은 리뷰 완료 하였는데, "bug-49924 REPLICATION_SENDER_IP가 hostname일때 서버 시작이 실패해야합니다." 버그 등록하였습니다. 이 부분에 대해서 좀 더 논의해 보고 의견 드리겠습니다.

현 상태로 매뉴얼은 반영하고 BUG-49924 관련하여 매뉴얼 변경이 필요하면 버그 완료 후에 수정하는 것이 어떨지요?

2022-09-06 00:34 UTC, lswhh commented
네 알겠습니다.

2022-09-07 11:16 UTC, hessalti commented
아래 버그를 7.1, 7.2, trunk 에 반영했습니다.
*** BUG-49924 REPLICATION_SENDER_IP가 hostname일때 서버 시작이 실패해야합니다.

2022-09-13 01:07 UTC, lswhh commented
"BUG-49924 REPLICATION_SENDER_IP가 hostname일때 서버 시작이 실패해야합니다." 도 완료되었으므로, 
"REPLICATION_SENDER_IP 값으로 호스트네임을 입력하면 이중화 시작이 실패한 상태로 Altibase 서버가 구동된다." 멘트 제거후 
반영하는 것이 좋을것 같습니다. 다른 부분은 리뷰 마쳤습니다. 
확인 부탁드립니다.

2022-09-13 04:32 UTC, eheejung commented
> 

IP 주소 형식에 맞지 않는 값을 입력하면 Altibase 서버 구동이 실패합니다. 

와 같은 형태로 변경하는 것은 어떨지요?

2022-09-13 04:32 UTC, eheejung commented
> "BUG-49924 REPLICATION_SENDER_IP가 hostname일때 서버 시작이 실패해야합니다." 도 완료되었으므로, "REPLICATION_SENDER_IP 값으로 호스트네임을 입력하면 이중화 시작이 실패한 상태로 Altibase 서버가 구동된다." 멘트 제거후 반영하는 것이 좋을것 같습니다. 다른 부분은 리뷰 마쳤습니다. 확인 부탁드립니다.

IP 주소 형식에 맞지 않는 값을 입력하면 Altibase 서버 구동이 실패합니다.

와 같은 형태로 변경하는 것은 어떨지요?

2022-09-13 07:59 UTC, lswhh commented
> IP 주소 형식에 맞지 않는 값을 입력하면 Altibase 서버 구동이 실패합니다.
> 와 같은 형태로 변경하는 것은 어떨지요?
--> 좋은 것 같습니다.

2022-09-19 08:02 UTC, scott-altibase approved these changes
수고하셨습니다

2022-09-19 08:08 UTC, eheejung approved these changes
리뷰 완료

2022-09-19 08:20 UTC, eheejung commented
@lswhh 이승원 팀장님- 매뉴얼 오픈은 태그 생성 시점에 맞춰 제가 직접 머지하려합니다. 확인 부탁드립니다-

2022-09-20 07:46 UTC, lswhh commented
네 수고하셨습니다. 감사합니다.

2022-09-22 08:17 UTC, merged