Bug 49952 regexp mode 관련 설명 개선
ALTIBASE/Documents pull request #292
Opened 2022-09-28 09:57 UTC by eheejung

채종빈님이 작성하신 초안 올립니다.

2022-11-07 09:37 UTC, eheejung commented
초안 수정하여 올립니다. 리뷰 부탁드립니다.

2022-11-08 01:59 UTC, eheejung commented
@scott-altibase 새롭게 추가된 부분 리뷰 부탁드립니다~

2022-11-08 08:01 UTC, chaealti reviewed
전체적인 내용은 적절하게 수정된 것 같습니다.
다만 SQL 레퍼런스와 에러 메제시 문서간 버전이 맞지 않는데 의도되지 않은 것이라면 수정 부탁드립니다.
의도된 것이라면 제가 달아둔 코멘트는 무시하셔도 됩니다.
1차 리뷰 마칩니다.

2022-11-09 03:37 UTC, scott-altibase requested changes
리뷰 남깁니다

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase의 정규 표현식 모드 중 Altibase 정규 표현식 모드에 대해 살펴보자.
살펴보자  ---> 매뉴얼에 쓰기에는 너무 구어체 같지 않나요?
살펴본다 or  설명한다 정도로 쓰는게 좋을것 같습니다

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase의 정규 표현식 모드 중 PCRE2 호환 모드에 대해 살펴보자.
살펴보자...위와 동일
살펴본다 or 설명한다 or 설명하고 있다

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +먼저, PCRE2 호환 모드는 아래와 같은 특징과 제약 사항이 있다.
먼저, --> 삭제하는게 좋을것 같습니다.
아니면 위에 제목을 특징 및 제약사항 으로 바꾸고 이 문장은 통채로 삭제해도 될것 같습니다

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +##### 간단한 어설션
assertion을 어설션이라고는 잘 안쓰는거 같던데
어서션이나 어써션이라고 많이 씁니다. 위키백과에도 어서션이라고 나와 있고
혹시 어설션을 참고한 곳이 있는 건가요?

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +찾고자 하는 문자가 몇 번 반복하는 지 지정하여 검색한다.
찾고자 하는 문자가 몇 번 반복하는 지 지정하여 검색한다.
>>찾고자 하는 문자가 몇 번 반복하는지 지정하여 검색한다.

2022-11-09 03:37 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이를 나타내는 대표적인 예이다.
Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이를 나타내는 대표적인 예이다.
>> Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이(보여준다)

2022-11-09 04:56 UTC, eheejung reviewed
전형진 실장님의 리뷰 반영하고 수정 불가한 부분 코멘트 남겼습니다. 
확인 부탁드립니다. 

빠른 리뷰 감사합니다~~

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +이 장에서 Altibase에서 지원하는 정규 표현식에 대해서 설명한다. 이 장에서 사용한 샘플 스키마는 $ALTIBASE_HOME/sample/APRE/schema/schema.sql를 이용하였다.
```suggestion
Altibase에서 지원하는 정규 표현식에 대해서 설명한다. 이 장에서 사용한 샘플 스키마는 $ALTIBASE_HOME/sample/APRE/schema/schema.sql를 이용하였다. 
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase의 정규 표현식 모드 중 Altibase 정규 표현식 모드에 대해 살펴보자.
```suggestion
Altibase에서 지원하는 정규 표현식 중 Altibase 정규 표현식 모드에 대해 설명한다.
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +먼저, PCRE2 호환 모드는 아래와 같은 특징과 제약 사항이 있다.
```suggestion
PCRE2 호환 모드는 아래와 같은 특징과 제약 사항이 있다.
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +##### 간단한 어설션
```suggestion
##### 간단한 어써션
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +어설션(assertions)은 어떤 문자 또는 문자열의 앞과 뒤를 확인하는 것을 의미한다. [메타 문자](#메타-문자-1)에서 소개한 "^"와 "$"는 어설션의 하나이며 '앵커'라고 부르기도 한다.
```suggestion
어써션(assertions)은 어떤 문자 또는 문자열의 앞과 뒤를 확인하는 것을 의미한다. [메타 문자](#메타-문자-1)에서 소개한 "^"와 "$"는 어설션의 하나이며 '앵커'라고 부르기도 한다. 
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +찾고자 하는 문자가 몇 번 반복하는 지 지정하여 검색한다.
```suggestion
찾고자 하는 문자가 몇 번 반복하는지 지정하여 검색한다. 
```

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이를 나타내는 대표적인 예이다.
> Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이를 나타내는 대표적인 예이다.
> 
> > > Altibase 정규 표현식 모드와 PCRE2 호환 모드의 정규 표현식 문법 차이(보여준다)

두 정규식의 모든 차이점을 보여주는 표가 아니라서, 혼동이 없도록 '대표적인 예'라고 표현이 필요했습니다.

2022-11-09 04:56 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +PCRE2 호환 모드에서 발생하는 에러 중 0x2106C 에러 코드는 아래와 같은 형식으로 에러 메시지가 출력된다. <1%s>는 PCRE2 라이브러리에서 반환한 메시지이며 <0%s>는 Altibase 에서 해당 에러가 발생한 위치를 의미한다. 이 에러 메시지에 대한 원인과 조치 방법은 Error Message Reference의 [15.Regular Ex
```suggestion
PCRE2 호환 모드에서 발생하는 에러 중 0x2106C 에러 코드는 아래와 같은 형식으로 에러 메시지가 출력된다. <1%s>는 PCRE2 라이브러리에서 반환한 메시지이며 <0%s>는 Altibase 에서 해당 에러가 발생한 위치를 의미한다. 이 에러 메시지에 대한 원인과 조치 방법은 Error Message Reference의 [15.Regular Expression Error Code](https://github.com/eheejung/ALTI_Documents/blob/master/Manuals/Altibase_7.1/kor/Error%20Message%20Reference.md#15regular-expression-error-code) 장에서 확인할 수 있다.
```

2022-11-09 04:57 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +##### 간단한 어설션
> assertion을 어설션이라고는 잘 안쓰는거 같던데 어서션이나 어써션이라고 많이 씁니다. 위키백과에도 어서션이라고 나와 있고 혹시 어설션을 참고한 곳이 있는 건가요?

정규표현식 assertion을 검색하면 어설션이라고 많이 쓰고 있습니다. 뭐든 상관없겠어서 어써션으로 반영했습니다~

2022-11-09 04:58 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +PCRE2 호환 모드에서 발생하는 에러 중 0x2106C 에러 코드는 아래와 같은 형식으로 에러 메시지가 출력된다. <1%s>는 PCRE2 라이브러리에서 반환한 메시지이며 <0%s>는 Altibase 에서 해당 에러가 발생한 위치를 의미한다. 이 에러 메시지에 대한 원인과 조치 방법은 Error Message Reference의 [15.Regular Ex
> 710 브랜치 SQL 레퍼런스 문서인데 에러 메세지 문서 링크가 trunk를 가리키고 있네요. 수정이 필요해보입니다.

수정합니다.

2022-11-09 05:00 UTC, eheejung commented on Manuals/Altibase_7.1/kor/SQL Reference.md
> +Altibase의 정규 표현식 모드 중 PCRE2 호환 모드에 대해 살펴보자.
```suggestion
Altibase에서 지원하는 정규 표현식 중 PCRE2 호환 모드에 대해 설명한다.
```

2022-11-09 05:01 UTC, eheejung reviewed
수정이 누락된 부분 추가

2022-11-11 07:46 UTC, scott-altibase approved these changes
확인하였습니다. 수고하셨습니다.

2022-11-16 05:40 UTC, chaealti approved these changes
전형진 실장님의 리뷰 반영되어 수정된 부분 확인했습니다.
특이 사항 없습니다.

2022-11-17 08:04 UTC, merged