BUG-50034
ALTIBASE/Documents pull request #316
Opened 2022-12-19 09:23 UTC by eheejung

**CLI 매뉴얼**
- "3.LOB 인터페이스 항목"에 LOB 데이터 처리 방식 설명을 추가했습니다.
- "LOB 데이터 타입" 항목도 수정하였습니다. "C 데이터 타입" 표에 SQL_C_CHAR, SQL_C_BINARY를 추가하였는데 적합한 지 검토 부탁드립니다.
- "SQLPutLob 항목"을 전체적으로 수정했습니다.
- "SQLPutLob 항목"에 추가하신 Partial Rollback 설명은 엄격하게 SQLExecute에서 발생하는 에러라 삭제하고 관련 내용을 3.LOB 인터페이스 항목에 추가했습니다.
- 기존 설명을 삭제하거나 변경하였으니 잘못된 부분이 있는지 자세히 리뷰해주시면 감사하겠습니다.

**Precompiler 매뉴얼**
- LOB 칼럼에 NOT NULL 제약사항이 있을 때 에러 발생 상황 설명 추가했습니다. 
- 기존 매뉴얼에 LOB Locator 관련한 설명이 전혀 없어 지금은 언급하지 않았고, 같은 문장을 JDBC 매뉴얼에도 동일하게 적용했습니다. 

**JDBC 매뉴얼**
- LOB 칼럼에 NOT NULL 제약사항이 있을 때 에러 발생 상황 설명 추가했습니다.

2022-12-19 09:38 UTC, eheejung commented
General Reference 매뉴얼 변경 부분 검토를 위해 서영준 팀장님 리뷰어 추가합니다.

2022-12-23 08:51 UTC, younjungpark approved these changes
JDBC 변경된 부분 확인했습니다.
수고하셨습니다.

2022-12-27 00:48 UTC, eheejung commented
@hscho-altibase @YoungheeBae 매뉴얼 리뷰 부탁드립니다.

2022-12-27 00:54 UTC, eheejung commented
@seo0jun General Reference 매뉴얼의 LOB [제한 사항](https://github.com/ALTIBASE/Documents/blob/BUG-50034-lob-not-null-constraint/Manuals/Altibase_7.1/kor/General%20Reference-1.Data%20Types%20%26%20Altibase%20Properties.md#%EC%A0%9C%ED%95%9C-%EC%82%AC%ED%95%AD) 중 마지막 제한 사항 변경 부분 리뷰 부탁드립니다.

2022-12-27 00:59 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
LOB 타입 칼럼의 값이 -> LOB 타입 칼럼의 값을 : 조사 바꿔야 할 것 같습니다.

2022-12-27 01:02 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +| SQLUINTEGER | fromPosition  | 입력 | LOB 데이터를 삽입 또는 갱신할 시작 위치로, 0부터 시작하며 LOB 데이터를 삽입할 때는 항상 0이다. 단위는 바이트이다. |
사용자가 써야 하는 것이므로 문구가 바뀌어야 할 것 같습니다.
LOB 데이터를 삽입할 때는 항상 0이다. -> LOB 데이터를 삽입할 때는 항상 0이어야 한다.

2022-12-27 01:04 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
아래와 같이 반영하겠습니다. 

```suggestion
아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값을 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.** 
```

2022-12-27 01:04 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
아래와 같이 반영하겠습니다. 

```suggestion
아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값을 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.** 
```

2022-12-27 01:05 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +UPDATE 문으로 LOB 타입 칼럼 전체를 갱신할 때 이 함수를 사용할 수 있다. 이 함수의 동작은 [LOB 데이터 삽입](#lob-데이터-삽입) 방식과 같으며 fromPosition도 항상 0이다.
fromPosition도 항상 0이다.  -> 갱신할 위치를 지정하므로 0이 아니어도 됩니다. 문구를 바꿔야 할 것 같습니다.

2022-12-27 01:07 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +UPDATE 문으로 LOB 타입 칼럼 전체를 갱신할 때 이 함수를 사용할 수 있다. 이 함수의 동작은 [LOB 데이터 삽입](#lob-데이터-삽입) 방식과 같으며 fromPosition도 항상 0이다.
> fromPosition도 항상 0이다. -> 갱신할 위치를 지정하므로 0이 아니어도 됩니다. 문구를 바꿔야 할 것 같습니다.

UPDATE문으로 LOB 타입 칼럼 전체를 갱신하는 경우와 SQLPutLob() 함수로 특정 위치부터 갱신하는 경우를 구분해서 설명했습니다. 그래서 전자의 경우는 항상 0인 것으로 이해했는데, 잘못 이해한 것인지요?

2022-12-27 01:11 UTC, YoungheeBae reviewed
코멘트 몇 개 남겼습니다

2022-12-27 01:12 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +| SQLUINTEGER | fromPosition  | 입력 | LOB 데이터를 삽입 또는 갱신할 시작 위치로, 0부터 시작하며 LOB 데이터를 삽입할 때는 항상 0이다. 단위는 바이트이다. |
```suggestion
| SQLUINTEGER | fromPosition  | 입력 | LOB 데이터를 삽입 또는 갱신할 시작 위치로, 0부터 시작하며 LOB 데이터를 삽입할 때는 0이어야 한다. 단위는 바이트이다. |
```

2022-12-27 01:15 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +UPDATE 문으로 LOB 타입 칼럼 전체를 갱신할 때 이 함수를 사용할 수 있다. 이 함수의 동작은 [LOB 데이터 삽입](#lob-데이터-삽입) 방식과 같으며 fromPosition도 항상 0이다.
> fromPosition도 항상 0이다. -> fromPosition도 0이어야 한다.

```suggestion
UPDATE 문으로 LOB 타입 칼럼 전체를 갱신할 때 이 함수를 사용할 수 있다. 이 함수의 동작은 [LOB 데이터 삽입](#lob-데이터-삽입) 방식과 같으며 fromPosition도  0이어야 한다. 
```

2022-12-27 01:19 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
아래와 같이 문구를 수정하면 어떨까 합니다.

LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다.
->
LOB 타입 칼럼이 있는 레코드의 LOB 타임 칼럼은 초기 값인 널 값으로 반영된다.

2022-12-27 01:20 UTC, eheejung commented
> 코멘트 몇 개 남겼습니다

검토해주셔서 감사합니다. 
의견 반영하여 Suggested change 로 남겼습니다. 모든 리뷰 완료 후에 커밋하겠습니다. 

CLI 매뉴얼에서 "3.LOB 인터페이스" 부분과 "SQLPutLob 함수"에서 기존 설명을 삭제하거나 변경한 부분이 있는데, 괜찮은가요? 이 부분 꼼꼼히 확인받고 싶어 재차 확인 요청합니다. ㅎㅎ

2022-12-27 01:21 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +INSERT 문으로 LOB 데이터를 삽입할 때 이 함수를 사용할 수 있다. 이때, fromPosition은 항상 0이다. 이것은 targetLocator가 길이가 0인 LOB 데이터를 가리키는 것을 의미한다.
```suggestion
INSERT 문으로 LOB 데이터를 삽입할 때 이 함수를 사용할 수 있다. 이때, fromPosition은 0이어야 한다. 이것은 targetLocator가 길이가 0인 LOB 데이터를 가리키는 것을 의미한다.
```

2022-12-27 01:28 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> -LOB Locator를 얻고자 한다면, 해당 LOB 칼럼의 타입에 따라서 SQL_C_CLOB_LOCATOR, 혹은 SQL_C_BLOB_LOCATOR를 적절하게 바인드하면 된다. 여기서 말하는 LOB Locator 즉, LOB 위치 입력기는 운영체제의 파일 포인터처럼 LOB 데이터를 연산할 때 사용되는 핸들이다.
이 부분은 수정된 아래 문구와 적절히 혼합하여 살리면 좋을 것 같습니다.  
"LOB 위치 입력기는 LOB 데이터를 가리키는 Altibase 서버의 내부 자료구조이며 트랜잭션에 종속된다."

2022-12-27 01:28 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
'초기'라는 단어를 사용해야 할까요? '초기'라는 단어를 매뉴얼이 굳이 사용해야 할 필요가 없어 보이는데.. 사용해야 한다면, 초기화된다.로 마치는 게 어떨까요?

LOB 타입 칼럼이 있는 레코드의 LOB 타임 칼럼은 널 값으로 초기화된다.

2022-12-27 01:29 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +SQLPutLob 함수를 사용하여 SQL 문을 사용하지 않고 기존 LOB 데이터에서 특정 위치의 값을 갱신할 수 있다. 이때, LOB 위치 입력기를 얻기 위해 SELECT *LOB_column_name* FROM *table_name* WHERE … FOR UPDATE 문장을 먼저 수행해야 한다. 이 함수의 동작 역시 [LOB 데이터 삽입](#lob-데이
SQL문을 사용해서 위치 입력기를 가져오기 때문에 SQL 문을 사용하지 않고 SQLPutLob 함수를 사용한다는 것이 명확하지 않아 보입니다.

2022-12-27 01:31 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
Lob locator를 사용하지 않는다면 에러가 발생하지 않으므로 가능성을 경고하는 수준으로 문구를 바꾸는 것이 어떨까요?
->
APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생할 수 있다.

2022-12-27 01:31 UTC, YoungheeBae reviewed
코멘트 더 남겼습니다. 나머지는 괜찮은 것 같습니다. 수고하셨습니다

2022-12-27 01:34 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
초기화는 이미 결과 1 수행 시에 발행했기 때문입니다. commit 하는 시점은 이미 초기화된 null이 반영되는 시점이라서 그렇게 표현했습니다. 왜 널 값 상태인지를 설명하려는 의도이니 그에 맞게 표현하면 될 것 같습니다.

2022-12-27 01:34 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
예제에 '초기화한다'는 문장이 있네요. 아래와 같이 변경할까 합니다.

```suggestion
아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드의 LOB 타입 칼럼은 널(null)로 초기화된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.** 
```

2022-12-27 01:34 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
예제에 '초기화한다'는 문장이 있네요. 아래와 같이 변경할까 합니다.

```suggestion
아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드의 LOB 타입 칼럼은 널(null)로 초기화된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.** 
```

2022-12-27 01:35 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +SQLPutLob 함수를 사용하여 SQL 문을 사용하지 않고 기존 LOB 데이터에서 특정 위치의 값을 갱신할 수 있다. 이때, LOB 위치 입력기를 얻기 위해 SELECT *LOB_column_name* FROM *table_name* WHERE … FOR UPDATE 문장을 먼저 수행해야 한다. 이 함수의 동작 역시 [LOB 데이터 삽입](#lob-데이
```suggestion
SQLPutLob 함수를 사용하여 기존 LOB 데이터에서 특정 위치의 값을 갱신할 수 있다. 이때, LOB 위치 입력기를 얻기 위해 SELECT *LOB_column_name* FROM *table_name* WHERE … FOR UPDATE 문장을 먼저 수행해야 한다. 이 함수의 동작 역시 [LOB 데이터 삽입](#lob-데이터-삽입) 방식과 같으나 fromPosition은 기존 LOB 데이터에서 갱신할 시작 위치를 지정해야 한다. fromPosition에 기존 LOB 데이터의 끝 위치를 지정하면, CLI 애플리케이션 버퍼(value)에 담긴 LOB 데이터가 기존 데이터 뒤에 추가된다. 
```

2022-12-27 01:37 UTC, eheejung commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
```suggestion
  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 위치 입력기를 사용하여 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
```

2022-12-27 01:37 UTC, eheejung commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
```suggestion
  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생할 수 있다.
```

2022-12-27 01:38 UTC, eheejung commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
더 명확하게 하거나 가능성을 알려주는 수준 중 무엇이 더 적합할까요?

2022-12-27 01:42 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> -LOB Locator를 얻고자 한다면, 해당 LOB 칼럼의 타입에 따라서 SQL_C_CLOB_LOCATOR, 혹은 SQL_C_BLOB_LOCATOR를 적절하게 바인드하면 된다. 여기서 말하는 LOB Locator 즉, LOB 위치 입력기는 운영체제의 파일 포인터처럼 LOB 데이터를 연산할 때 사용되는 핸들이다.
문장을 제안해주실 수 있을까요?

참고로.. 아래 문장은..

LOB Locator를 얻고자 한다면, 해당 LOB 칼럼의 타입에 따라서 SQL_C_CLOB_LOCATOR, 혹은 SQL_C_BLOB_LOCATOR를 적절하게 바인드하면 된다.

[c-데이터-타입](https://github.com/ALTIBASE/Documents/blob/BUG-50034-lob-not-null-constraint/Manuals/Altibase_7.1/kor/CLI%20User's%20Manual.md#c-%EB%8D%B0%EC%9D%B4%ED%84%B0-%ED%83%80%EC%9E%85)에 같은 문장이 있습니다.

2022-12-27 01:46 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> -LOB Locator를 얻고자 한다면, 해당 LOB 칼럼의 타입에 따라서 SQL_C_CLOB_LOCATOR, 혹은 SQL_C_BLOB_LOCATOR를 적절하게 바인드하면 된다. 여기서 말하는 LOB Locator 즉, LOB 위치 입력기는 운영체제의 파일 포인터처럼 LOB 데이터를 연산할 때 사용되는 핸들이다.
네, 확인했습니다.

2022-12-27 01:50 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
APRE와 JDBC에서는 locator를 사용자가 직접 사용하지는 않기 때문에 그냥 가능성 정도로만 써도 괜찮을 거 같아요

2022-12-27 01:55 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +SQLPutLob 함수를 사용하여 SQL 문을 사용하지 않고 기존 LOB 데이터에서 특정 위치의 값을 갱신할 수 있다. 이때, LOB 위치 입력기를 얻기 위해 SELECT *LOB_column_name* FROM *table_name* WHERE … FOR UPDATE 문장을 먼저 수행해야 한다. 이 함수의 동작 역시 [LOB 데이터 삽입](#lob-데이
확인했습니다

2022-12-27 01:58 UTC, hscho-altibase approved these changes
수고 많으셨습니다. 수정 감사합니다.

2022-12-27 01:59 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +아래 표에서 `결과 1`에서 커밋을 수행하면, LOB 타입 칼럼이 있는 레코드는 LOB 타입 칼럼이 널 값으로 반영된다. LOB 타입 칼럼의 값이 널 상태로 남기지 않으려면 **반드시 트랜잭션을 롤백해야 한다.**
> 초기화는 이미 결과 1 수행 시에 발행했기 때문입니다. commit 하는 시점은 이미 초기화된 null이 반영되는 시점이라서 그렇게 표현했습니다. 왜 널 값 상태인지를 설명하려는 의도이니 그에 맞게 표현하면 될 것 같습니다.

LOB 위치 입력기를 얻어올 때 항상 초기화하는 것이 아니라서, (초기화는 insert 할 때만 한다고 확인 받았습니다.) .. 관련 부분을 수정하려고 합니다. 
수정 완료 후 다시 한 번 리뷰 부탁드립니다.

2022-12-27 02:04 UTC, eheejung commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생한다.
> APRE와 JDBC에서는 locator를 사용자가 직접 사용하지는 않기 때문에 그냥 가능성 정도로만 써도 괜찮을 거 같아요

의견 감사합니다~~~~

2022-12-27 03:32 UTC, YoungheeBae approved these changes
모두 확인했습니다. 수고하셨습니다.

2023-01-16 05:12 UTC, eheejung commented
@hscho-altibase @YoungheeBae 바쁘시겠지만 한 번 더 리뷰 부탁드립니다. 
LOB 데이터 처리 방식에서 널 초기화 관련 부분에서 부족한 부분이 있어 설명 추가하였습니다. 
SQLPutLob 함수 예제에서 예제 제목 변경, 예제 순서 변경, 널 초기화 관련한 주석 추가 했습니다. 

부탁드립니다. 감사합니다.

2023-01-16 06:04 UTC, hscho-altibase approved these changes
네 확인하였습니다.

2023-01-16 06:04 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생할 수 있다.
서버에서 직접 처리하는 경우가 있기 때문에 이렇게 표현하는 게 맞을 것 같습니다.

2023-01-16 06:56 UTC, seo0jun reviewed
수고하셨습니다.

2023-01-17 01:30 UTC, eheejung commented on Manuals/Altibase_7.1/kor/General Reference-1.Data Types & Altibase Properties.md
> +  LOB 타입 칼럼에 NOT NULL 제약조건을 정의할 수 있으나 APRE, CLI, JDBC 애플리케이션에서 LOB 데이터 처리 시 제약조건 위배 에러가 발생할 수 있다.
네 반영했습니다~

2023-01-17 02:15 UTC, eheejung commented
@YoungheeBae 님~ 바쁘시겠지만 한 번 더 리뷰 부탁드립니다.
LOB 데이터 처리 방식에서 널 초기화 관련 부분에서 부족한 부분이 있어 설명 추가하였습니다.
SQLPutLob 함수 예제에서 예제 제목 변경, 예제 순서 변경, 널 초기화 관련한 주석 추가 했습니다.

부탁드립니다. 감사합니다.

2023-01-17 05:49 UTC, hscho-altibase reviewed
몇 가지 의견 남겼습니다.

2023-01-17 05:49 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻는다. */
BindParameter에서 Lob Locator를 얻는 게 아니고, 아래 구문의 Execute 단계에서 얻기 위해 bind만 하는 단계입니다.
아래와 같이 수정되어야 할 것 같습니다.
"LOB 위치 입력기를 얻기 위해 Bind한다." 정도로 하면 될 것 같습니다.

2023-01-17 05:49 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻는다. */
아래 쪽에 이미 컴멘트 남겼습니다. 동일하게 적용하면 될 것 같습니다.

2023-01-17 05:49 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +> **SQL 수행 결과가 달라지는 예시**
결과가 달라진다는 어감 보다는, 수행 시 주의 사항 정도로 환기 시키면 어떨까 싶습니다.

2023-01-17 06:42 UTC, eheejung reviewed
@hscho-altibase 리뷰 반영하여 Suggested change 올렸습니다. 확인 부탁드립니다. 감사합니다.~

2023-01-17 06:42 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻는다. */
```suggestion
/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻기 위해 LOB 위치 입력기 인자를 바인드한다. */
```

2023-01-17 06:42 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻는다. */
```suggestion
/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻기 위해 LOB 위치 입력기 인자를 바인드한다. */
```

2023-01-17 06:42 UTC, eheejung commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +> **SQL 수행 결과가 달라지는 예시**
```suggestion
> **LOB 위치 입력기를 이용한 트랜잭션 커밋 시 주의사항**
```

2023-01-17 06:46 UTC, hscho-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +> **SQL 수행 결과가 달라지는 예시**
수정된 부분 모두 확인하였습니다. 수고 많으셨습니다.

2023-01-18 04:57 UTC, eheejung commented
@scott-altibase 기존 매뉴얼에서 변경이 많아 QA팀 팀장님 리뷰어 추가합니다. 
MM팀 리뷰 막바지 단계입니다. 
리뷰 부탁드립니다. 감사합니다.

2023-01-18 05:38 UTC, YoungheeBae commented on Manuals/Altibase_7.1/kor/Precompiler User's Manual.md
> +> 만약 CLOB 칼럼에 NOT NULL 제약 조건이 있다면, INSERT 문 수행 시 [Unable to insert (or update) NULL into NOT NULL column.] 에러가 발생한다. APRE_CLOB 타입은 내부적으로 LOB 데이터를 삽입하기 전에 CLOB 칼럼을 널(null)로 초기화하기 때문이다. 이것은 LOB 데이터 타입의
CLI 매뉴얼에는 "INSERT 또는 UPDATE 문 수행시" 라고 되어 있네요. 여기도 UPDATE 문 추가해야 할 거 같습니다. 위 JDBC 매뉴얼도요..

2023-01-18 05:39 UTC, YoungheeBae approved these changes
코멘트 하나 남겼습니다. 수고하셨습니다.

2023-01-18 05:45 UTC, eheejung reviewed
배영희님 리뷰 확인하고 JDBC, Precompiler 매뉴얼 수정합니다.

2023-01-18 05:45 UTC, eheejung commented on Manuals/Altibase_7.1/kor/JDBC User's Manual.md
> +LOB 칼럼에 NOT NULL 제약 조건이 있다면, INSERT 문을 수행하는 PreparedStatement.execute() 또는 PreparedStatement.executeUpdate()에서 [Unable to insert (or update) NULL into NOT NULL column.] 에러가 발생한다. JDBC는 LOB 데이터를 삽입하기
```suggestion
LOB 칼럼에 NOT NULL 제약 조건이 있다면, INSERT와 UPDATE 문을 수행하는 PreparedStatement.execute() 또는 PreparedStatement.executeUpdate()에서 [Unable to insert (or update) NULL into NOT NULL column.] 에러가 발생한다. JDBC는 LOB 데이터를 처리하기 전에 내부적으로 CLOB 칼럼을 널(null)로 초기화하기 때문이다. 이것은 LOB 데이터 타입의 제약 사항으로, 관련 내용은 [General Reference](https://github.com/ALTIBASE/Documents/blob/BUG-50034/Manuals/Altibase_7.1/kor/General%20Reference-1.Data%20Types%20%26%20Altibase%20Properties.md#%EC%A0%9C%ED%95%9C-%EC%82%AC%ED%95%AD) 매뉴얼에서 확인할 수 있다.
```

2023-01-18 05:45 UTC, eheejung commented on Manuals/Altibase_7.1/kor/Precompiler User's Manual.md
> +> 만약 BLOB 칼럼에 NOT NULL 제약 조건이 있다면, INSERT 문 수행 시 [Unable to insert (or update) NULL into NOT NULL column.] 에러가 발생한다. APRE_BLOB 타입은 내부적으로 LOB 데이터를 삽입하기 전에  BLOB 칼럼을 널(null)로 초기화하기 때문이다. 이것은 LOB 데이터 타입
```suggestion
> 만약 BLOB 칼럼에 NOT NULL 제약 조건이 있다면, INSERT와 UPDATE 문 수행 시 [Unable to insert (or update) NULL into NOT NULL column.] 에러가 발생한다. APRE_BLOB 타입은 LOB 데이터를 처리하기 전에 내부적으로 BLOB 칼럼을 널(null)로 초기화하기 때문이다. 이것은 LOB 데이터 타입의 제약 사항으로, 관련 내용은 [General Reference](https://github.com/ALTIBASE/Documents/blob/BUG-50034/Manuals/Altibase_7.1/kor/General%20Reference-1.Data%20Types%20%26%20Altibase%20Properties.md#%EC%A0%9C%ED%95%9C-%EC%82%AC%ED%95%AD) 매뉴얼에서 확인할 수 있다.
```

2023-01-19 08:16 UTC, scott-altibase requested changes

2023-01-19 08:16 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindParameter 함수에서 LOB 위치 입력기를 얻는다. */
"SQLBindParameter 함수에서 LOB 위치 입력기를 얻기 위해" 서가 아니라 아래의 SQLExecute에서 LOB 위치 입력기를 얻기 위해 LOB위치 입력기 인자를 바인딩 한다가 맞을것 같네요

2023-01-19 08:16 UTC, scott-altibase commented on Manuals/Altibase_7.1/kor/CLI User's Manual.md
> +/* SQLBindCol 함수에서 LOB 위치 입력기를 얻는다. */
여기도 위의 SQLBindParameter와 같이 아래와 같이 수정해야 하지 않을까 합니다
/* SQLExecute 함수에서 LOB 위치 입력기를 얻기 위해 LOB 위치 입력기 인자를 바인딩한다. */

2023-01-19 09:26 UTC, eheejung reviewed
@scott-altibase 리뷰 확인하고 반영했습니다. 확인 부탁드립니다.~

2023-01-30 02:20 UTC, scott-altibase approved these changes
수고하셨습니다

2023-01-30 10:25 UTC, merged