Chkim task 7473 postgre sql 9.5.3
ALTIBASE/Documents pull request #335
Opened 2023-01-30 02:22 UTC by eheejung

BUG-50123 [ux-migrationCenter] TASK-7473 MigrationCenter for PostgreSQL 9.5.3 매뉴얼 적용

2023-01-30 23:57 UTC, eheejung reviewed
Suggested change 로 초안 리뷰 올립니다. 
검토 부탁드립니다.
감사합니다.

2023-01-30 23:57 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | BIT VARYING | VARBIT | PostgreSQL BIT VARYING 데이터 타입 최대 컬럼 크기는 83,886,080으로 알티베이스 VARBIT 최대치인 64,000을 초과한다. 컬럼 크기가 64,000 이하인 경우 VARBIT 타입으로, 초과하는 경우는 CLOB 타입으로 매핑된다. |
```suggestion
| 22 | BIT VARYING | VARBIT 또는 CLOB | PostgreSQL의 BIT VARYING 칼럼 크기가 64,000비트 이하이면 VARBIT 타입으로, 64,000비트를 초과하면 CLOB으로 변환한다. 이는 PostgreSQL과 Altibase의 데이터 타입 간에 최대 크기 차이로 마이그레이션 시 발생할 수 있는 데이터 손실을 방지하기 위해서이다. PostgreSQL의 BIT VARYING 최대 크기는 83,886,080비트로 Altibase의 64,000비트 보다 크다. |
```

2023-01-30 23:57 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | XML | CLOB | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 CLOB R타입으로 저장된다. |
"CLOB R타입"에서 'R'은 오타일까요?

```suggestion
| 23  | XML | CLOB | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 CLOB R타입으로 저장된다. |
```

2023-01-30 23:57 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | CIRCLE | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
```suggestion
| 24 | JSON | CLOB | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 CLOB 타입으로 저장된다. |
| 25 | JSONB | BLOB | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 BLOB 타입으로 저장된다. |
| 26 | ENUM | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 27 | UUID | VARCHAR(36) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 28 | ARRAY | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 29 | COMPOSITE | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 30 | RANGE | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 31 | POINT | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 32 | LINE | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 33 | LSEG | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 34 | BOX | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 35 | PATH | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 36 | POLYGON | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
| 37 | CIRCLE | VARCHAR(32000) | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR타입으로 저장된다. |
```

2023-01-30 23:57 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| -------------- | ------------------------ |
```suggestion
| Character Set  | Max. Bytes Per Character |
| :-------------- | :------------------------: |
```

2023-01-30 23:57 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_12_Release_Notes.md
> +PostgreSQL 9.5.3 버전을 원본 데이터 베이스로 지원한다.
```suggestion
지원하는 원본 데이터베이스에 PostgreSQL 9.5.3이 추가되었다.
```

2023-01-31 00:46 UTC, eheejung reviewed
누락한 부분이 있어 추가로 올립니다.

2023-01-31 00:46 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| Sequence               |                   O                   |                  O/X                   | PostgreSQL와 Altibase간 두가지 차이점이 있다.<br />첫째, PostgreSQL sequence의 기본 최대값은 922337203685477580
```suggestion
| Sequence               |                   O                   |                  X                   | PostgreSQ 시퀀스의 최대값의 기본값은 9223372036854775807은 Altibase 시퀀스의 최대값의 기본값 9223372036854775806으로 강제 변환된다.<br/><br/>

PostgreSQL 시퀀스의 cache size가 1이면 Altibase에서 CACHE 절이 삭제되고 Altibase의 기본 cache size 20으로 생성된다.<br/><br/>

'Build Table'에서 사용자가 명시적으로 생성한 시퀀스는 마이그레이션 대상에서 제외되나, 마이그레이션 대상 테이블 칼럼의 Serial data type을 위해 생성된 시퀀스는 테이블과 함께 마이그레이션된다. |
```

2023-01-31 00:46 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | BIT | BIT | PostgreSQL BIT 데이터 타입 최대 컬럼 크기는 83,886,080으로 알티베이스 BIT 최대치인 64,000을 초과한다. 컬럼 크기가 64,000 이하인 경우 BIT 타입으로, 초과하는 경우는 CLOB 타입으로 매핑된다. |
```suggestion
| 21 | BIT | BIT | PostgreSQL의 BIT 칼럼 크기가 64,000비트 이하면 BIT로, 64,000비트를 초과하면 CLOB으로 변환한다. 이는 PostgreSQL과 Altibase의 데이터 타입 간에 최대 크기 차이로 마이그레이션 시 발생할 수 있는 데이터 손실을 방지하기 위해서이다. PostgreSQL의 BIT 최대 크기는 83,886,080비트로 Altibase의 64,000비트 보다 크다.|
```

2023-01-31 00:46 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | BOOLEAN | CHAR(1) | Altibase에는 PostgreSQL의 boolean과 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 문자형으로 저장된다. true -> 't', false -> 'f', unknown -> null 값으로 치환된다. |
```suggestion
| 11 | BOOLEAN | CHAR(1) | PostgreSQL의 BOOLEAN은 CHAR(1)으로 변환한다. true는 't'로, false는 'f로 변환하여 저장하며 unknown은 널(null)로 저장한다.|
```

2023-01-31 00:46 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +|      | CHARACTER VARYING | VARCHAR  | PostgreSQL VARCHAR(n)에서 문자형 컬럼 길이가 자동 보정된 값이  알티베이스 최대치 (32,000)보다 작으면 VARCHAR로, 최대치를 넘어서면 CLOB으로 매핑된다. |
```suggestion
|  8    | CHARACTER <br/> CHAR | CHAR |  |
|  9    | CHARACTER VARYING <br/> VARCHAR | VARCHAR 또는 CLOB| PostgreSQL와 Altibase의 문자 집합에 따라 마이그레이션 센터에 의해 자동 보정된 칼럼 길이가 32,000바이트보다 작으면 VARCHAR로, 32,000바이트를 초과하면 CLOB으로 변환한다. 32,000바이트는 Altibase의 VARCHAR 타입의 최대 크기이다. |
```

2023-01-31 04:33 UTC, zennken commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | XML | CLOB | Altibase에는 호환되는 데이터 타입이 없으므로, 데이터 손실을 막기 위해 CLOB R타입으로 저장된다. |
네~오타입니다. CLOB으로 수정 부탁드립니다.

2023-01-31 04:34 UTC, zennken commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| Sequence               |                   O                   |                  O/X                   | PostgreSQL와 Altibase간 두가지 차이점이 있다.<br />첫째, PostgreSQL sequence의 기본 최대값은 922337203685477580
PostgreSQ 시퀀스의 최대값의 기본값은 9223372036854775807은
->  ...은...은 반복되고 있어 아래와 같이 수정하면 어떨까 합니다.
PostgreSQ 시퀀스의 최대값 기본값_인_ 9223372036854775807은

2023-01-31 04:39 UTC, zennken commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | BIT | BIT | PostgreSQL BIT 데이터 타입 최대 컬럼 크기는 83,886,080으로 알티베이스 BIT 최대치인 64,000을 초과한다. 컬럼 크기가 64,000 이하인 경우 BIT 타입으로, 초과하는 경우는 CLOB 타입으로 매핑된다. |
BIT VARYING과 동일한 포멧으로 변환하기 위해, 대상 데이터 타입을 BIT -> BIT 또는 CLOB으로 변경하는 게 어떨까 합니다.

2023-01-31 05:10 UTC, zennken reviewed
수고하셨습니다. 특히 MySQL, Oracle BINARY DOUBLE 원복 부분 부탁드립니다.
감사합니다.

2023-01-31 05:10 UTC, zennken commented on Manuals/Tools/Altibase_trunk/eng/Migration Center User's Manual.md
> +|  9   | BINARY DOUBLE | DOUBLE          | Since +Inf, -Inf, and NaN values are not stored in Altibase's DOUBLE, loss may occur during migration. |
이 부분은 검증되지 않아서 예전 내용으로 다시 원복해야 할 것 같습니다.
BUG-49993에서 처리했어야 하는데, 바쁜 이슈가 많다보니 아직 검증을 못했네요.
죄송합니다.

2023-01-31 05:10 UTC, zennken commented on Manuals/Tools/Altibase_trunk/eng/Migration Center User's Manual.md
> +|  13  | DOUBLE                          | DOUBLE         |                                                              |
이 부분은 검증되지 않아서 예전 내용으로 다시 원복해야 할 것 같습니다.
BUG-49993에서 처리했어야 하는데, 바쁜 이슈가 많다보니 아직 검증을 못했네요.
죄송합니다.

2023-01-31 05:10 UTC, zennken commented on Manuals/Tools/Altibase_trunk/eng/Migration Center User's Manual.md
> +|  9   | BINARY DOUBLE | DOUBLE          | Since +Inf, -Inf, and NaN values are not stored in Altibase's DOUBLE, loss may occur during migration. |
MySQL, Oracle BINARY_DOUBLE 한글 매뉴얼도 원복 부탁드립니다.

2023-01-31 07:05 UTC, eheejung reviewed
피드백 반영하여 Suggested change 로 올렸습니다. 확인 부탁드립니다. 감사합니다.

2023-01-31 07:05 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| Sequence               |                   O                   |                  O/X                   | PostgreSQL와 Altibase간 두가지 차이점이 있다.<br />첫째, PostgreSQL sequence의 기본 최대값은 922337203685477580
```suggestion
| Sequence               |                   O                   |                  X                   | PostgreSQL 시퀀스의 기본 최대값 9223372036854775807은 Altibase 시퀀스의 기본 최대값 9223372036854775806으로 강제 변환된다.<br/><br/>
	
	PostgreSQL 시퀀스의 캐시 값이 1이면 Altibase에서 CACHE 절이 삭제되고 Altibase의 기본 캐시 값 20으로 생성된다.<br/><br/>
	
	'Build Table'에서 사용자가 명시적으로 생성한 시퀀스는 마이그레이션 대상에서 제외되나, 마이그레이션 대상 테이블 칼럼의 Serial data type을 위해 생성된 시퀀스는 테이블과 함께 마이그레이션된다. |
```

2023-01-31 07:05 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +|  9   | BINARY DOUBLE | DOUBLE            | +Inf, -Inf, and NaN 값들은 알티베이스에서 표현되지 않기 때문에 마이그레이션 중 손실이 일어날 수 있다. |
```suggestion
|  8   | BINARY FLOAT  | FLOAT             |                                                              |
|  9   | BINARY DOUBLE | VARCHAR(310)      | Altibase 에는 오라클 BINARY DOUBLE 타입과 호환되는 데이터 타입이 없으므로 데이터 손실을 막기 위해 문자 형으로 저장된다. |
```

2023-01-31 07:05 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +|  13  | DOUBLE             | DOUBLE                          | TODO: BUG-49993                                              |
> MySQL DOUBLE은 유효자리수가 17자리이고 Altibase는 유효자리수가 17자리입니다. 이로 인해 정밀도 손실이 있을 수 있습니다. 이렇게 한 이유는 INC-47001에서 고객 요청으로 변경했습니다. 정밀도 부분은 매뉴얼에 기재하면 좋을 것 같습니다. https://altra.altibase.com/altimis-2.0/app_review/review_view.jsp?id=14401

이번 릴리즈에 반영되는 버그 대상이 아닌가요? 맞다면 버그 처리되면 수정하겠습니다.

2023-01-31 07:05 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +| | BIT | BIT | PostgreSQL BIT 데이터 타입 최대 컬럼 크기는 83,886,080으로 알티베이스 BIT 최대치인 64,000을 초과한다. 컬럼 크기가 64,000 이하인 경우 BIT 타입으로, 초과하는 경우는 CLOB 타입으로 매핑된다. |
```suggestion
| | BIT | BIT 또는 CLOB | PostgreSQL BIT 데이터 타입 최대 컬럼 크기는 83,886,080으로 알티베이스 BIT 최대치인 64,000을 초과한다. 컬럼 크기가 64,000 이하인 경우 BIT 타입으로, 초과하는 경우는 CLOB 타입으로 매핑된다. |
```

2023-02-02 05:16 UTC, zennken reviewed
희정님 리뷰 부탁드립니다.

2023-02-02 05:19 UTC, eheejung reviewed
피드백 반영하여 Suggested change 등록 후에 커밋하고 웹에서 확인하고 다시 남기겠습니다.

2023-02-02 05:19 UTC, eheejung commented on ReleaseNotes/kor/Altibase_Migration_Center_7_12_Release_Notes.md
> +
```suggestion
### BUG-50092 프라이머리 키 컬럼의 정렬 조건이 마이그레이션되지 않습니다.

프라이머리 키 컬럼의 정렬 조건은 기본적으로 오름차순이지만 내림차순을 지원하는 데이터베이스가 있다. 내림차순 정렬 속성도 마이그레이션 되도록 수정한다.
```

2023-02-02 05:19 UTC, eheejung commented on Manuals/Tools/Altibase_trunk/kor/Migration Center User's Manual.md
> +|  13  | DOUBLE             | DOUBLE                          | TODO: BUG-49993                                              |
```suggestion
|  13  | DOUBLE            | VARCHAR(310) | Altibase에는 MySQL DOUBLE 타입과 호환 가능한 데이터 타입이 없으므로, 데이터 손실을 막기 위해 VARCHAR 타입으로 맵핑된다. |
```

2023-02-03 00:52 UTC, scott-altibase requested changes

2023-02-03 00:52 UTC, scott-altibase commented on ReleaseNotes/kor/Altibase_Migration_Center_7_12_Release_Notes.md
> +Migration Center는 데이터베이스 마이그레이션을 위한 도구로서, 사용자가 편리하게 써드파티 데이터베이스를 알티베이스 데이터베이스 또는 외부 파일로 이관하거나 알티베이스 데이터베이스를 오라클 데이터베이스로 이관하도록 한다. 보통 데이터베이스 마이그레이션은 수동으로 진행할 경우 복잡하고 시간이 많이 소요되며 휴먼 에러가 발생하는 불편함이 있다. 이
아래와 같이 수정하는것이 더 자연스러울것 같습니다.
복잡하고 시간이 많이 소요되며 휴먼 에러가 발생하는 불편함이 있다. 이를 효율화하기 위해 
-> 휴먼 에러가 발생할 가능성이 크다. 이를 예방하기 위해
마우스 클릭 몇 번만으로 데이터베이스 마이그레이션을 가능하게 한다.  
-> 마이그레이션을 수행할 수 있도록 지원한다.

2023-02-03 01:02 UTC, zennken commented on ReleaseNotes/kor/Altibase_Migration_Center_7_12_Release_Notes.md
> +Migration Center는 데이터베이스 마이그레이션을 위한 도구로서, 사용자가 편리하게 써드파티 데이터베이스를 알티베이스 데이터베이스 또는 외부 파일로 이관하거나 알티베이스 데이터베이스를 오라클 데이터베이스로 이관하도록 한다. 보통 데이터베이스 마이그레이션은 수동으로 진행할 경우 복잡하고 시간이 많이 소요되며 휴먼 에러가 발생하는 불편함이 있다. 이
복잡하고 시간이 많이 소요되며 휴먼 에러가 발생하는 불편함이 있다. 이를 효율화하기 위해
-> 휴먼 에러가 발생할 가능성이 크다. 이를 예방하기 위해
--> 변경하는 게 좋을 것 같습니다.

마우스 클릭 몇 번만으로 데이터베이스 마이그레이션을 가능하게 한다.
-> 마이그레이션을 수행할 수 있도록 지원한다.
--> 권고하신대로 표현하면 중복표현이 될 것 같습니다. 원래 표현을 그대로 하는 것이 좋을 것 같습니다. 
이를 효율화하기 위해 Migration Center는 GUI 모드에서 마이그레이션을 수행할 수 있도록 지원한다. 이에 더하여, 자원 사용을 최적화하기 위해 CLI 모드도 지원한다.

2023-02-03 01:28 UTC, scott-altibase approved these changes
수고하셨습니다

2023-02-03 01:35 UTC, zennken commented
전형진 실장님의 의견 반영하려 릴리즈 노트 커밋했습니다.

2023-02-03 01:38 UTC, zennken approved these changes
수고하셨습니다.

2023-02-03 05:37 UTC, zennken commented
금일 희정님 휴가인 관계로 제가 merge 하도록 하겠습니다.
수고하셨습니다.

2023-02-03 05:38 UTC, merged