BUG-50622 반영
ALTIBASE/Documents pull request #440
Opened 2023-09-25 10:07 UTC by jina-altibase

BUG-50622 반영 및 프로퍼티 순서 변경

2023-10-04 02:27 UTC, Joseph-Kwak requested changes
Attributes of PSM_CASE_SENSITIVE_MODE are Read-Write, Single Value.


Its value can be changed using the ALTER SYSTEM statement.
=> The value of this property can be changed using the ALTER SYSTEM statement while Altibase is running.

2023-10-05 07:08 UTC, Joseph-Kwak approved these changes

2023-10-05 07:09 UTC, jina-altibase commented
리뷰 내용 반영하여 재 수정하였습니다~. 확인해주세요~

2023-10-13 04:50 UTC, scott-altibase requested changes
수고하셨습니다

2023-10-13 04:50 UTC, scott-altibase commented on Manuals/Altibase_7.3/kor/General_Reference-1.Data Types & Altibase Properties.md
> +  때
윗줄하고 같은 줄로 하면 좋을것 같네요

2023-10-13 04:50 UTC, scott-altibase commented on Manuals/Altibase_7.3/kor/General_Reference-1.Data Types & Altibase Properties.md
> +  명시하지 않을 때
이것도 윗줄이랑 한줄로 해도 될것 같네요

2023-10-13 05:58 UTC, jina-altibase commented on Manuals/Altibase_7.3/kor/General_Reference-1.Data Types & Altibase Properties.md
> +  때
네, 반영했습니다~

2023-10-13 05:58 UTC, jina-altibase commented on Manuals/Altibase_7.3/kor/General_Reference-1.Data Types & Altibase Properties.md
> +  명시하지 않을 때
네, 반영했습니다~

2023-10-13 05:58 UTC, merged